import { makeAutoObservable } from "mobx";

import { ArmorKit, CurrentArmorInfo } from "@/utils/storeInterfaces";

import { armorBonuses } from "@/data/armor/bonuses";

class ArmorKitsStore {
  currentArmorInfo = {} as CurrentArmorInfo;

  armorKits: ArmorKit[] = [
    {
      id: 1,
      imagePath: "/static/ArmorKits/SC30.png",
      typeIndex: 0,
      devName: "SC-30 Trailblazer Scout",
      obtainingMethodIndex: 7,
      price: 85,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.scout,
    },
    {
      id: 2,
      imagePath: "/static/ArmorKits/SC34.png",
      typeIndex: 0,
      devName: "SC-34 Infiltrator",
      obtainingMethodIndex: 7,
      price: 5,
      armorRating: 70,
      speed: 530,
      staminaRegen: 115,
      bonus: armorBonuses.scout,
    },
    {
      id: 3,
      imagePath: "/static/ArmorKits/SC37.png",
      typeIndex: 0,
      devName: "SC-37 Legionnaire",
      obtainingMethodIndex: 6,
      price: 225,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.servoAssisted,
    },
    {
      id: 4,
      imagePath: "/static/ArmorKits/CE07.webp",
      typeIndex: 0,
      devName: "CE-07 Demolition Specialist",
      obtainingMethodIndex: 10,
      price: 80,
      armorRating: 64,
      speed: 536,
      staminaRegen: 118,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 5,
      imagePath: "/static/ArmorKits/CE67.png",
      typeIndex: 0,
      devName: "CE-67 Titan",
      obtainingMethodIndex: 6,
      price: 225,
      armorRating: 79,
      speed: 521,
      staminaRegen: 111,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 6,
      imagePath: "/static/ArmorKits/CE74.webp",
      typeIndex: 0,
      devName: "CE-74 Breaker",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 7,
      imagePath: "/static/ArmorKits/Fs37RavagerImage.webp",
      typeIndex: 0,
      devName: "FS-37 Ravager",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 8,
      imagePath: "/static/ArmorKits/FS38.png",
      typeIndex: 0,
      devName: "FS-38 Eradicator",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.fortification,
    },
    {
      id: 9,
      imagePath: "/static/ArmorKits/B08.png",
      typeIndex: 0,
      devName: "B-08 Light Gunner",
      obtainingMethodIndex: 6,
      price: 225,
      armorRating: 100,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.extraPadding,
    },
    {
      id: 10,
      imagePath: "/static/ArmorKits/CM21.png",
      typeIndex: 0,
      devName: "CM-21 Trench Paramedic",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 64,
      speed: 536,
      staminaRegen: 118,
      bonus: armorBonuses.medKit,
    },
    {
      id: 11,
      imagePath: "/static/ArmorKits/EX00.png",
      typeIndex: 0,
      devName: "EX-00 Prototype X",
      obtainingMethodIndex: 9,
      price: 112,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.electricalCondult,
    },
    {
      id: 12,
      imagePath: "/static/ArmorKits/CW4.png",
      typeIndex: 0,
      devName: "CW-4 Arctic Ranger",
      obtainingMethodIndex: 11,
      price: 112,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.scout,
    },
    {
      id: 13,
      imagePath: "/static/ArmorKits/PH9.png",
      typeIndex: 0,
      devName: "PH-9 Predator",
      obtainingMethodIndex: 12,
      price: 70,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.peakPhisique,
    },
    {
      id: 14,
      imagePath: "/static/ArmorKits/I09.png",
      typeIndex: 0,
      devName: "I-09 Heatseeker",
      obtainingMethodIndex: 13,
      price: 70,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.inflammable,
    },
    {
      id: 15,
      imagePath: "/static/ArmorKits/AF50.png",
      typeIndex: 0,
      devName: "AF-50 Noxious Ranger",
      obtainingMethodIndex: 14,
      price: 75,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.advancedFiltration,
    },
    {
      id: 16,
      imagePath: "/static/ArmorKits/UF16.png",
      typeIndex: 0,
      devName: "UF-16 Inspector",
      obtainingMethodIndex: 15,
      price: 140,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.unflinching,
    },
    {
      id: 17,
      imagePath: "/static/ArmorKits/AC2.png",
      typeIndex: 0,
      devName: "AC-2 Obedient",
      obtainingMethodIndex: 17,
      price: 0,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.acclimated,
    },
    {
      id: 18,
      imagePath: "/static/ArmorKits/SR24.png",
      typeIndex: 0,
      devName: "SR-24 Street Scout",
      obtainingMethodIndex: 16,
      price: 30,
      armorRating: 50,
      speed: 550,
      staminaRegen: 125,
      bonus: armorBonuses.siegeReady,
    },
    {
      id: 19,
      imagePath: "/static/ArmorKits/B01.png",
      typeIndex: 1,
      devName: "B-01 Tactical",
      obtainingMethodIndex: 0,
      price: 0,
      armorRating: 150,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.extraPadding,
    },
    {
      id: 20,
      imagePath: "/static/ArmorKits/DP00.png",
      typeIndex: 1,
      devName: "DP-00 Tactical",
      obtainingMethodIndex: 1,
      price: 0,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.democracyProtects,
    },
    {
      id: 21,
      imagePath: "/static/ArmorKits/DP11.png",
      typeIndex: 1,
      devName: "DP-11 Champion of the People",
      obtainingMethodIndex: 7,
      price: 175,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.democracyProtects,
    },
    {
      id: 22,
      imagePath: "/static/ArmorKits/DP40.png",
      typeIndex: 1,
      devName: "DP-40 Hero of the Federation",
      obtainingMethodIndex: 7,
      price: 45,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.democracyProtects,
    },
    {
      id: 23,
      imagePath: "/static/ArmorKits/DP53.webp",
      typeIndex: 1,
      devName: "DP-53 Savior of the Free",
      obtainingMethodIndex: 3,
      price: 0,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.democracyProtects,
    },
    {
      id: 24,
      imagePath: "/static/ArmorKits/CW9.png",
      typeIndex: 1,
      devName: "CW-9 White Wolf",
      obtainingMethodIndex: 6,
      price: 450,
      armorRating: 150,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.extraPadding,
    },
    {
      id: 25,
      imagePath: "/static/ArmorKits/CE27.webp",
      typeIndex: 1,
      devName: "CE-27 Ground Breaker",
      obtainingMethodIndex: 10,
      price: 30,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 26,
      imagePath: "/static/ArmorKits/CE35.png",
      typeIndex: 1,
      devName: "CE-35 Trench Engineer",
      obtainingMethodIndex: 7,
      price: 17,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 27,
      imagePath: "/static/ArmorKits/CE81.png",
      typeIndex: 1,
      devName: "CE-81 Juggernaut",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 28,
      imagePath: "/static/ArmorKits/SC15.webp",
      typeIndex: 1,
      devName: "SC-15 Drone Master",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 29,
      imagePath: "/static/ArmorKits/CM09.png",
      typeIndex: 1,
      devName: "CM-09 Bonesnapper",
      obtainingMethodIndex: 7,
      price: 27,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.medKit,
    },
    {
      id: 30,
      imagePath: "/static/ArmorKits/CM10.png",
      typeIndex: 1,
      devName: "CM-10 Clinician",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.medKit,
    },
    {
      id: 31,
      imagePath: "/static/ArmorKits/CM14.png",
      typeIndex: 1,
      devName: "CM-14 Physician",
      obtainingMethodIndex: 7,
      price: 120,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.medKit,
    },
    {
      id: 32,
      imagePath: "/static/ArmorKits/Tr7AmbassadorOfTheBrandImage.webp",
      typeIndex: 1,
      devName: "TR-7 Ambassador of the Brand",
      obtainingMethodIndex: 2,
      price: 0,
      armorRating: 150,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.extraPadding,
    },
    {
      id: 33,
      imagePath: "/static/ArmorKits/Tr9CavalierOfDemocracyImage.webp",
      typeIndex: 1,
      devName: "TR-9 Cavalier of Democracy",
      obtainingMethodIndex: 2,
      price: 0,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.democracyProtects,
    },
    {
      id: 34,
      imagePath: "/static/ArmorKits/TR40.png",
      typeIndex: 1,
      devName: "TR-40 Gold Eagle",
      obtainingMethodIndex: 4,
      price: 0,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.extraPadding,
    },
    {
      id: 35,
      imagePath: "/static/ArmorKits/TR117.png",
      typeIndex: 1,
      devName: "TR-117 Alpha Commander",
      obtainingMethodIndex: 5,
      price: 0,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.medKit,
    },
    {
      id: 36,
      imagePath: "/static/ArmorKits/SA04.png",
      typeIndex: 1,
      devName: "SA-04 Combat Technician",
      obtainingMethodIndex: 7,
      price: 100,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.scout,
    },
    {
      id: 37,
      imagePath: "/static/ArmorKits/SA12.png",
      typeIndex: 1,
      devName: "SA-12 Servo Assisted",
      obtainingMethodIndex: 8,
      price: 80,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.servoAssisted,
    },
    {
      id: 38,
      imagePath: "/static/ArmorKits/SA25.png",
      typeIndex: 1,
      devName: "SA-25 Steel Trooper",
      obtainingMethodIndex: 8,
      price: 30,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.servoAssisted,
    },
    {
      id: 39,
      imagePath: "/static/ArmorKits/EX03.png",
      typeIndex: 1,
      devName: "EX-03 Prototype 3",
      obtainingMethodIndex: 9,
      price: 30,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.electricalCondult,
    },
    {
      id: 40,
      imagePath: "/static/ArmorKits/EX16.png",
      typeIndex: 1,
      devName: "EX-16 Prototype 16",
      obtainingMethodIndex: 9,
      price: 80,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.electricalCondult,
    },
    {
      id: 41,
      imagePath: "/static/ArmorKits/FS34.png",
      typeIndex: 1,
      devName: "FS-34 Exterminator",
      obtainingMethodIndex: 6,
      price: 600,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.fortification,
    },
    {
      id: 42,
      imagePath: "/static/ArmorKits/B24.png",
      typeIndex: 1,
      devName: "B-24 Enforcer",
      obtainingMethodIndex: 6,
      price: 225,
      armorRating: 129,
      speed: 471,
      staminaRegen: 71,
      bonus: armorBonuses.fortification,
    },
    {
      id: 43,
      imagePath: "/static/ArmorKits/PH56.png",
      typeIndex: 1,
      devName: "PH-56 Jaguar",
      obtainingMethodIndex: 6,
      price: 225,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.peakPhisique,
    },
    {
      id: 44,
      imagePath: "/static/ArmorKits/I92.png",
      typeIndex: 1,
      devName: "I-92 Fire Fighter",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.inflammable,
    },
    {
      id: 45,
      imagePath: "/static/ArmorKits/I102.png",
      typeIndex: 1,
      devName: "I-102 Draconaught",
      obtainingMethodIndex: 13,
      price: 375,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.inflammable,
    },
    {
      id: 46,
      imagePath: "/static/ArmorKits/AF02.png",
      typeIndex: 1,
      devName: "AF-02 Haz-Master",
      obtainingMethodIndex: 14,
      price: 80,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.advancedFiltration,
    },
    {
      id: 47,
      imagePath: "/static/ArmorKits/AF91.png",
      typeIndex: 1,
      devName: "AF-91 Field Chemist",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.advancedFiltration,
    },
    {
      id: 48,
      imagePath: "/static/ArmorKits/UF50.png",
      typeIndex: 1,
      devName: "UF-50 Bloodhound",
      obtainingMethodIndex: 15,
      price: 80,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.unflinching,
    },
    {
      id: 49,
      imagePath: "/static/ArmorKits/UF84.png",
      typeIndex: 1,
      devName: "UF-84 Doubt Killer",
      obtainingMethodIndex: 6,
      price: 600,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.unflinching,
    },
    {
      id: 50,
      imagePath: "/static/ArmorKits/AC1.png",
      typeIndex: 1,
      devName: "AC-1 Dutiful",
      obtainingMethodIndex: 17,
      price: 600,
      armorRating: 100,
      speed: 500,
      staminaRegen: 100,
      bonus: armorBonuses.acclimated,
    },
    {
      id: 51,
      imagePath: "/static/ArmorKits/FS05.png",
      typeIndex: 2,
      devName: "FS-05 Marksman",
      obtainingMethodIndex: 7,
      price: 11,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.fortification,
    },
    {
      id: 52,
      imagePath: "/static/ArmorKits/FS11.png",
      typeIndex: 2,
      devName: "FS-11 Executioner",
      obtainingMethodIndex: 6,
      price: 225,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.fortification,
    },
    {
      id: 53,
      imagePath: "/static/ArmorKits/FS23.png",
      typeIndex: 2,
      devName: "FS-23 Battle Master",
      obtainingMethodIndex: 7,
      price: 60,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.fortification,
    },
    {
      id: 54,
      imagePath: "/static/ArmorKits/FS55.png",
      typeIndex: 2,
      devName: "FS-55 Devastator",
      obtainingMethodIndex: 10,
      price: 112,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.fortification,
    },
    {
      id: 55,
      imagePath: "/static/ArmorKits/FS61.png",
      typeIndex: 2,
      devName: "FS-61 Dreadnought",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.servoAssisted,
    },
    {
      id: 56,
      imagePath: "/static/ArmorKits/SA32.png",
      typeIndex: 2,
      devName: "SA-32 Dynamo",
      obtainingMethodIndex: 8,
      price: 112,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.servoAssisted,
    },
    {
      id: 57,
      imagePath: "/static/ArmorKits/CW22.png",
      typeIndex: 2,
      devName: "CW-22 Kodiak",
      obtainingMethodIndex: 11,
      price: 80,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.fortification,
    },
    {
      id: 58,
      imagePath: "/static/ArmorKits/CW36.png",
      typeIndex: 2,
      devName: "CW-36 Winter Warrior",
      obtainingMethodIndex: 11,
      price: 30,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.servoAssisted,
    },
    {
      id: 59,
      imagePath: "/static/ArmorKits/Tr62KnightImage.webp",
      typeIndex: 2,
      devName: "TR-62 Knight",
      obtainingMethodIndex: 2,
      price: 0,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.servoAssisted,
    },
    {
      id: 60,
      imagePath: "/static/ArmorKits/B27.png",
      typeIndex: 2,
      devName: "B-27 Fortified Commando",
      obtainingMethodIndex: 6,
      price: 600,
      armorRating: 200,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.extraPadding,
    },
    {
      id: 61,
      imagePath: "/static/ArmorKits/CE64.png",
      typeIndex: 2,
      devName: "CE-64 Grenadier",
      obtainingMethodIndex: 6,
      price: 450,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 62,
      imagePath: "/static/ArmorKits/CE101.png",
      typeIndex: 2,
      devName: "CE-101 Guerilla Gorilla",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.engineerKit,
    },
    {
      id: 63,
      imagePath: "/static/ArmorKits/CM17.png",
      typeIndex: 2,
      devName: "CM-17 Butcher",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.medKit,
    },
    {
      id: 64,
      imagePath: "/static/ArmorKits/PH202.png",
      typeIndex: 2,
      devName: "PH-202 Twigsnapper",
      obtainingMethodIndex: 12,
      price: 80,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.peakPhisique,
    },
    {
      id: 65,
      imagePath: "/static/ArmorKits/I44.png",
      typeIndex: 2,
      devName: "I-44 Salamander",
      obtainingMethodIndex: 6,
      price: 375,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.inflammable,
    },
    {
      id: 66,
      imagePath: "/static/ArmorKits/AF52.png",
      typeIndex: 2,
      devName: "AF-52 Lockdown",
      obtainingMethodIndex: 6,
      price: 650,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.inflammable,
    },
    {
      id: 67,
      imagePath: "/static/ArmorKits/SR18.png",
      typeIndex: 2,
      devName: "SR-18 Roadblock",
      obtainingMethodIndex: 16,
      price: 650,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.siegeReady,
    },
    {
      id: 68,
      imagePath: "/static/ArmorKits/SR64.png",
      typeIndex: 2,
      devName: "SR-64 Cinderblock",
      obtainingMethodIndex: 6,
      price: 650,
      armorRating: 150,
      speed: 450,
      staminaRegen: 50,
      bonus: armorBonuses.siegeReady,
    },
  ];

  constructor() {
    makeAutoObservable(this);
  }

  clearCurrentArmorInfo() {
    this.currentArmorInfo = {} as CurrentArmorInfo;
  }
}

export const armorStore = new ArmorKitsStore();
