import { makeAutoObservable } from "mobx";

import { armorBonuses } from "@/data/armor/bonuses";
import { obtainingTypes } from "@/data/obtainingTypes";

import { ArmorKit, CurrentArmorInfo } from "@/utils/storeInterfaces";
import { getIntlArray } from "@/utils/generalFunctions";

class ArmorKitsStore {
  currentArmorInfo = {} as CurrentArmorInfo;

  translationFunction = (key: string) => key;

  armorKits: { [key: string]: ArmorKit[] } = {
    light: [
      {
        id: 1,
        imagePath: "/static/ArmorKits/SC30.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 85,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.scout,
      },
      {
        id: 2,
        imagePath: "/static/ArmorKits/SC34.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 5,
        armorRating: 70,
        speed: 530,
        staminaRegen: 115,
        bonus: armorBonuses.scout,
      },
      {
        id: 3,
        imagePath: "/static/ArmorKits/SC37.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 225,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.servoAssisted,
      },
      {
        id: 4,
        imagePath: "/static/ArmorKits/CE07.webp",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[10],
        price: 80,
        armorRating: 64,
        speed: 536,
        staminaRegen: 118,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 5,
        imagePath: "/static/ArmorKits/CE67.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 225,
        armorRating: 79,
        speed: 521,
        staminaRegen: 111,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 6,
        imagePath: "/static/ArmorKits/CE74.webp",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 7,
        imagePath: "/static/ArmorKits/Fs37RavagerImage.webp",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 8,
        imagePath: "/static/ArmorKits/FS38.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.fortification,
      },
      {
        id: 9,
        imagePath: "/static/ArmorKits/B08.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 225,
        armorRating: 100,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.extraPadding,
      },
      {
        id: 10,
        imagePath: "/static/ArmorKits/CM21.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 64,
        speed: 536,
        staminaRegen: 118,
        bonus: armorBonuses.medKit,
      },
      {
        id: 11,
        imagePath: "/static/ArmorKits/EX00.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[9],
        price: 112,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.electricalCondult,
      },
      {
        id: 12,
        imagePath: "/static/ArmorKits/CW4.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[11],
        price: 112,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.scout,
      },
      {
        id: 13,
        imagePath: "/static/ArmorKits/PH9.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[12],
        price: 70,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.peakPhisique,
      },
      {
        id: 14,
        imagePath: "/static/ArmorKits/I09.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[13],
        price: 70,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.inflammable,
      },
      {
        id: 15,
        imagePath: "/static/ArmorKits/AF50.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[14],
        price: 75,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.advancedFiltration,
      },
      {
        id: 16,
        imagePath: "/static/ArmorKits/UF16.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[15],
        price: 140,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.unflinching,
      },
      {
        id: 17,
        imagePath: "/static/ArmorKits/AC2.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[17],
        price: 0,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.acclimated,
      },
      {
        id: 18,
        imagePath: "/static/ArmorKits/SR24.png",
        type: "Легкая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[16],
        price: 30,
        armorRating: 50,
        speed: 550,
        staminaRegen: 125,
        bonus: armorBonuses.siegeReady,
      },
    ],
    medium: [
      {
        id: 19,
        imagePath: "/static/ArmorKits/B01.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[0],
        price: 0,
        armorRating: 150,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.extraPadding,
      },
      {
        id: 20,
        imagePath: "/static/ArmorKits/DP00.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[1],
        price: 0,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.democracyProtects,
      },
      {
        id: 21,
        imagePath: "/static/ArmorKits/DP11.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 175,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.democracyProtects,
      },
      {
        id: 22,
        imagePath: "/static/ArmorKits/DP40.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 45,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.democracyProtects,
      },
      {
        id: 23,
        imagePath: "/static/ArmorKits/DP53.webp",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[3],
        price: 0,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.democracyProtects,
      },
      {
        id: 24,
        imagePath: "/static/ArmorKits/CW9.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 450,
        armorRating: 150,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.extraPadding,
      },
      {
        id: 25,
        imagePath: "/static/ArmorKits/CE27.webp",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[10],
        price: 30,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 26,
        imagePath: "/static/ArmorKits/CE35.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 17,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 27,
        imagePath: "/static/ArmorKits/CE81.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 28,
        imagePath: "/static/ArmorKits/SC15.webp",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 29,
        imagePath: "/static/ArmorKits/CM09.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 27,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.medKit,
      },
      {
        id: 30,
        imagePath: "/static/ArmorKits/CM10.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.medKit,
      },
      {
        id: 31,
        imagePath: "/static/ArmorKits/CM14.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 120,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.medKit,
      },
      {
        id: 32,
        imagePath: "/static/ArmorKits/Tr7AmbassadorOfTheBrandImage.webp",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[2],
        price: 0,
        armorRating: 150,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.extraPadding,
      },
      {
        id: 33,
        imagePath: "/static/ArmorKits/Tr9CavalierOfDemocracyImage.webp",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[2],
        price: 0,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.democracyProtects,
      },
      {
        id: 34,
        imagePath: "/static/ArmorKits/TR40.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[4],
        price: 0,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.extraPadding,
      },
      {
        id: 35,
        imagePath: "/static/ArmorKits/TR117.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[5],
        price: 0,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.medKit,
      },
      {
        id: 36,
        imagePath: "/static/ArmorKits/SA04.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 100,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.scout,
      },
      {
        id: 37,
        imagePath: "/static/ArmorKits/SA12.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[8],
        price: 80,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.servoAssisted,
      },
      {
        id: 38,
        imagePath: "/static/ArmorKits/SA25.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[8],
        price: 30,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.servoAssisted,
      },
      {
        id: 39,
        imagePath: "/static/ArmorKits/EX03.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[9],
        price: 30,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.electricalCondult,
      },
      {
        id: 40,
        imagePath: "/static/ArmorKits/EX16.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[9],
        price: 80,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.electricalCondult,
      },
      {
        id: 41,
        imagePath: "/static/ArmorKits/FS34.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 600,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.fortification,
      },
      {
        id: 42,
        imagePath: "/static/ArmorKits/B24.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 225,
        armorRating: 129,
        speed: 471,
        staminaRegen: 71,
        bonus: armorBonuses.fortification,
      },
      {
        id: 43,
        imagePath: "/static/ArmorKits/PH56.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 225,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.peakPhisique,
      },
      {
        id: 44,
        imagePath: "/static/ArmorKits/I92.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.inflammable,
      },
      {
        id: 45,
        imagePath: "/static/ArmorKits/I102.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[13],
        price: 375,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.inflammable,
      },
      {
        id: 46,
        imagePath: "/static/ArmorKits/AF02.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[14],
        price: 80,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.advancedFiltration,
      },
      {
        id: 47,
        imagePath: "/static/ArmorKits/AF91.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.advancedFiltration,
      },
      {
        id: 48,
        imagePath: "/static/ArmorKits/UF50.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[15],
        price: 80,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.unflinching,
      },
      {
        id: 49,
        imagePath: "/static/ArmorKits/UF84.png",
        type: "Средняя броня",
        name: "UF-84 «Убийца сомнений»",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 600,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.unflinching,
      },
      {
        id: 50,
        imagePath: "/static/ArmorKits/AC1.png",
        type: "Средняя броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[17],
        price: 600,
        armorRating: 100,
        speed: 500,
        staminaRegen: 100,
        bonus: armorBonuses.acclimated,
      },
    ],
    heavy: [
      {
        id: 51,
        imagePath: "/static/ArmorKits/FS05.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 11,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.fortification,
      },
      {
        id: 52,
        imagePath: "/static/ArmorKits/FS11.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 225,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.fortification,
      },
      {
        id: 53,
        imagePath: "/static/ArmorKits/FS23.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[7],
        price: 60,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.fortification,
      },
      {
        id: 54,
        imagePath: "/static/ArmorKits/FS55.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[10],
        price: 112,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.fortification,
      },
      {
        id: 55,
        imagePath: "/static/ArmorKits/FS61.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.servoAssisted,
      },
      {
        id: 56,
        imagePath: "/static/ArmorKits/SA32.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[8],
        price: 112,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.servoAssisted,
      },
      {
        id: 57,
        imagePath: "/static/ArmorKits/CW22.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[11],
        price: 80,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.fortification,
      },
      {
        id: 58,
        imagePath: "/static/ArmorKits/CW36.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[11],
        price: 30,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.servoAssisted,
      },
      {
        id: 59,
        imagePath: "/static/ArmorKits/Tr62KnightImage.webp",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[2],
        price: 0,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.servoAssisted,
      },
      {
        id: 60,
        imagePath: "/static/ArmorKits/B27.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 600,
        armorRating: 200,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.extraPadding,
      },
      {
        id: 61,
        imagePath: "/static/ArmorKits/CE64.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 450,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 62,
        imagePath: "/static/ArmorKits/CE101.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.engineerKit,
      },
      {
        id: 63,
        imagePath: "/static/ArmorKits/CM17.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.medKit,
      },
      {
        id: 64,
        imagePath: "/static/ArmorKits/PH202.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[12],
        price: 80,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.peakPhisique,
      },
      {
        id: 65,
        imagePath: "/static/ArmorKits/I44.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 375,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.inflammable,
      },
      {
        id: 66,
        imagePath: "/static/ArmorKits/AF52.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 650,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.inflammable,
      },
      {
        id: 67,
        imagePath: "/static/ArmorKits/SR18.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[16],
        price: 650,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.siegeReady,
      },
      {
        id: 68,
        imagePath: "/static/ArmorKits/SR64.png",
        type: "Тяжелая броня",
        obtainingMethod: getIntlArray(
          this.translationFunction("obtainingMethods"),
        )[6],
        price: 650,
        armorRating: 150,
        speed: 450,
        staminaRegen: 50,
        bonus: armorBonuses.siegeReady,
      },
    ],
  };

  constructor() {
    makeAutoObservable(this);
  }

  setTranslationFunction(t: (key: string) => string) {
    this.translationFunction = t;

    console.log(t("obtainingMethods"));
  }

  changeCurrentArmorInfo(id: number, armorType: string) {
    this.currentArmorInfo = { id: id, type: armorType };
  }

  clearCurrentArmorInfo() {
    this.currentArmorInfo = {} as CurrentArmorInfo;
  }
}

export const armorStore = new ArmorKitsStore();
