import { makeAutoObservable } from "mobx";

import { galaxySectors } from "@/data/galaxySectors";
import { weatherConditions } from "@/data/planetWeatherConditions";
import { biomes } from "@/data/planetBiomes";

import { CurrentPlanetInfo } from "@/utils/storeInterfaces";

class PlanetsStore {
  currentPlanetInfo = {} as CurrentPlanetInfo;

  planets = {
    0: {
      id: 1,
      name: "Супер-Земля",
      sector: galaxySectors.sol,
      biome: biomes.superEarth,
      weatherConditions: [],
      image: "",
    },
    1: {
      id: 2,
      name: "Марс",
      sector: galaxySectors.sol,
      biome: null,
      weatherConditions: [],
      image: "",
    },
    2: {
      id: 1,
      name: "Клен Дахт II",
      sector: galaxySectors.altus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Клен_Дахт_II.svg",
    },
    3: {
      id: 2,
      name: "Следопыт V",
      sector: galaxySectors.altus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Следопыт_V.svg",
    },
    4: {
      id: 3,
      name: "Вдовья гавань",
      sector: galaxySectors.altus,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Вдовья_гавань.svg",
    },
    5: {
      id: 4,
      name: "Новая гавань",
      sector: galaxySectors.altus,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Новая_гавань.svg",
    },
    6: {
      id: 5,
      name: "Пилен V",
      sector: galaxySectors.altus,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Пилен_V.svg",
    },
    7: {
      id: 1,
      name: "Гидропад прайм",
      sector: galaxySectors.barnard,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Гидропад_прайм.svg",
    },
    8: {
      id: 1,
      name: "Зея ругозия",
      sector: galaxySectors.ferris,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Зея_ругозия.svg",
    },
    9: {
      id: 2,
      name: "Дерроуспорт",
      sector: galaxySectors.barnard,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Дерроуспорт.svg",
    },
    10: {
      id: 3,
      name: "Форнскогур II",
      sector: galaxySectors.barnard,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Форнскогур_II.svg",
    },
    11: {
      id: 4,
      name: "Мидасбург",
      sector: galaxySectors.barnard,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Мидасбург.svg",
    },
    12: {
      id: 1,
      name: "Цербер IIIc",
      sector: galaxySectors.cancri,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Цербер_IIIc.svg",
    },
    13: {
      id: 2,
      name: "Водопады процветания",
      sector: galaxySectors.cancri,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Водопады_процветания.svg",
    },
    14: {
      id: 1,
      name: "Окул VI",
      sector: galaxySectors.gothmar,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Окул_VI.svg",
    },
    15: {
      id: 1,
      name: "Залив мучеников",
      sector: galaxySectors.cantolus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Залив_мучеников.svg",
    },
    16: {
      id: 2,
      name: "Пик свободы",
      sector: galaxySectors.cantolus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Пик_свободы.svg",
    },
    17: {
      id: 1,
      name: "Форт единения",
      sector: galaxySectors.orion,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Форт_единения.svg",
    },
    18: {
      id: 3,
      name: "Кельвинор",
      sector: galaxySectors.cantolus,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Кельвинор.svg",
    },
    19: {
      id: 1,
      name: "Призрак",
      sector: galaxySectors.idun,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Призрак.svg",
    },
    20: {
      id: 1,
      name: "Игла",
      sector: galaxySectors.kelvin,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Игла.svg",
    },
    21: {
      id: 2,
      name: "Новая кируна",
      sector: galaxySectors.kelvin,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Новая_кируна.svg",
    },
    22: {
      id: 3,
      name: "Форт правосудия",
      sector: galaxySectors.kelvin,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Форт_правосудия.svg",
    },
    23: {
      id: 4,
      name: "Зегемский рай",
      sector: galaxySectors.kelvin,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Загемский_рай.svg",
    },
    24: {
      id: 1,
      name: "Провидение",
      sector: galaxySectors.iptus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Провидение.svg",
    },
    25: {
      id: 2,
      name: "Примортия",
      sector: galaxySectors.iptus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Примортия.svg",
    },
    26: {
      id: 1,
      name: "Сульфура",
      sector: galaxySectors.celeste,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Сульфура.svg",
    },
    27: {
      id: 2,
      name: "Нублария I",
      sector: galaxySectors.celeste,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Нублария_I.svg",
    },
    28: {
      id: 3,
      name: "Кракату",
      sector: galaxySectors.celeste,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Кракату.svg",
    },
    29: {
      id: 1,
      name: "Вольтерра",
      sector: galaxySectors.korpus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Вольтерра.svg",
    },
    30: {
      id: 2,
      name: "Горн",
      sector: galaxySectors.korpus,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Горн.svg",
    },
    31: {
      id: 5,
      name: "Вуаль",
      sector: galaxySectors.barnard,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Вуаль.svg",
    },
    32: {
      id: 6,
      name: "Марр IV",
      sector: galaxySectors.barnard,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Марр_IV.svg",
    },
    33: {
      id: 3,
      name: "Форт безопасности",
      sector: galaxySectors.cancri,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Форт_безопасности.svg",
    },
    34: {
      id: 4,
      name: "Сейшельский пляж",
      sector: galaxySectors.cancri,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Сейшельский_пляж.svg",
    },
    35: {
      id: 1,
      name: "Хеллмейр",
      imageCount: 3,
      sector: galaxySectors.mirin,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Хеллмейр.svg",
    },
    36: {
      id: 5,
      name: "Эффлувия",
      sector: galaxySectors.cancri,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Эффлувия.svg",
    },
    37: {
      id: 2,
      name: "Солгаст",
      sector: galaxySectors.gothmar,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Солгаст.svg",
    },
    38: {
      id: 3,
      name: "Дилувия",
      sector: galaxySectors.gothmar,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Дилувия.svg",
    },
    39: {
      id: 4,
      name: "Виридия-прайм",
      sector: galaxySectors.cantolus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Виридия-прайм.svg",
    },
    40: {
      id: 5,
      name: "Обари",
      sector: galaxySectors.cantolus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Обари.svg",
    },
    41: {
      id: 2,
      name: "Мирадеш",
      sector: galaxySectors.idun,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Мирадеш.svg",
    },
    42: {
      id: 3,
      name: "Атрама",
      sector: galaxySectors.idun,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Атрама.svg",
    },
    43: {
      id: 5,
      name: "Эмерия",
      sector: galaxySectors.kelvin,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Эмерия.svg",
    },
    44: {
      id: 1,
      name: "Барабос",
      sector: galaxySectors.marspira,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Барабос.svg",
    },
    45: {
      id: 2,
      name: "Фенмейр",
      sector: galaxySectors.marspira,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Фенмейр.svg",
    },
    46: {
      id: 3,
      name: "Мастия",
      sector: galaxySectors.marspira,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Мастия.svg",
    },
    47: {
      id: 1,
      name: "Шаллус",
      sector: galaxySectors.talus,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Шаллус.svg",
    },
    48: {
      id: 3,
      name: "Кракабос",
      sector: galaxySectors.iptus,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Кракабос.svg",
    },
    49: {
      id: 4,
      name: "Иридика",
      sector: galaxySectors.iptus,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Иридика.svg",
    },
    50: {
      id: 2,
      name: "Астерра",
      sector: galaxySectors.orion,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Астерра.svg",
    },
    51: {
      id: 1,
      name: "Азур II",
      sector: galaxySectors.sten,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Азур_II.svg",
    },
    52: {
      id: 4,
      name: "Айвис",
      sector: galaxySectors.celeste,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Айвис.svg",
    },
    53: {
      id: 5,
      name: "Слиф",
      sector: galaxySectors.celeste,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Слиф.svg",
    },
    54: {
      id: 3,
      name: "Карамур",
      sector: galaxySectors.korpus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Карамур.svg",
    },
    55: {
      id: 1,
      name: "Кхарст",
      sector: galaxySectors.gallux,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Кхарст.svg",
    },
    56: {
      id: 1,
      name: "Юкория",
      sector: galaxySectors.morgon,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Юкория.svg",
    },
    57: {
      id: 2,
      name: "Мириум",
      sector: galaxySectors.morgon,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Мириум.svg",
    },
    58: {
      id: 1,
      name: "Керт II",
      sector: galaxySectors.rictus,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Керт_II.svg",
    },
    59: {
      id: 2,
      name: "Парш",
      sector: galaxySectors.rictus,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Парш.svg",
    },
    60: {
      id: 1,
      name: "Риф",
      sector: galaxySectors.saleria,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Риф.svg",
    },
    61: {
      id: 2,
      name: "Ирулта",
      sector: galaxySectors.saleria,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Ирулта.svg",
    },
    62: {
      id: 1,
      name: "Эморат",
      sector: galaxySectors.meridian,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Эморат.svg",
    },
    63: {
      id: 2,
      name: "Илдуна-прайм",
      sector: galaxySectors.meridian,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Илдуна-прайм.svg",
    },
    64: {
      id: 4,
      name: "Утроба",
      sector: galaxySectors.idun,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Утроба.svg",
    },
    65: {
      id: 1,
      name: "Меридия",
      tidbit: `<p>Одна из четырех планет, где была развернута система терминального контроля (TCS) - сеть массивных башен, которые покрывают планету нейротоксином, известным как Терминцид. Установка этих башен TCS потребовала совместных усилий многих Адских Десантников и в конечном итоге привела к тому, что терминиды были удалены навсегда.</p>`,
      sector: galaxySectors.umlaut,
      biome: biomes.meridia,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Меридия.svg",
    },
    66: {
      id: 1,
      name: "Борея",
      sector: galaxySectors.sagan,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Борея.svg",
    },
    67: {
      id: 4,
      name: "Курия",
      sector: galaxySectors.marspira,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Курия.svg",
    },
    68: {
      id: 5,
      name: "Тарш",
      sector: galaxySectors.marspira,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Тарш.svg",
    },
    69: {
      id: 2,
      name: "Шелт",
      sector: galaxySectors.talus,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Шелт.svg",
    },
    70: {
      id: 3,
      name: "Имбер",
      sector: galaxySectors.talus,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Имбер.svg",
    },
    71: {
      id: 1,
      name: "Блистика",
      sector: galaxySectors.gellert,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Блистика.svg",
    },
    72: {
      id: 5,
      name: "Ратч",
      sector: galaxySectors.iptus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Ратч.svg",
    },
    73: {
      id: 1,
      name: "Юльхейм",
      sector: galaxySectors.nanos,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Юльхейм.svg",
    },
    74: {
      id: 6,
      name: "Валгаард",
      sector: galaxySectors.iptus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Валгаард.svg",
    },
    75: {
      id: 1,
      name: "Арктур",
      sector: galaxySectors.arturion,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Арктур.svg",
    },
    76: {
      id: 1,
      name: "Эскер",
      sector: galaxySectors.falstaff,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Эскер.svg",
    },
    77: {
      id: 3,
      name: "Терек",
      sector: galaxySectors.orion,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Терек.svg",
    },
    78: {
      id: 4,
      name: "Сиррус",
      sector: galaxySectors.orion,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Сиррус.svg",
    },
    79: {
      id: 1,
      name: "Кримсика",
      imageCount: 3,
      sector: galaxySectors.draco,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Кримсика.svg",
    },
    80: {
      id: 5,
      name: "Хиит",
      sector: galaxySectors.orion,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Хиит.svg",
    },
    81: {
      id: 6,
      name: "Вельд",
      sector: galaxySectors.orion,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Вельд.svg",
    },
    82: {
      id: 4,
      name: "Альта V",
      sector: galaxySectors.korpus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Альта_V.svg",
    },
    83: {
      id: 1,
      name: "Урсика XI",
      sector: galaxySectors.borgus,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Урсика_XI.svg",
    },
    84: {
      id: 5,
      name: "Инари",
      sector: galaxySectors.korpus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Инари.svg",
    },
    85: {
      id: 1,
      name: "Скааш",
      sector: galaxySectors.ursa,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Скааш.svg",
    },
    86: {
      id: 6,
      name: "Морадеш",
      sector: galaxySectors.celeste,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Морадеш.svg",
    },
    87: {
      id: 2,
      name: "Расп",
      sector: galaxySectors.gallux,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Расп.svg",
    },
    88: {
      id: 3,
      name: "Башир",
      sector: galaxySectors.gallux,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Башир.svg",
    },
    89: {
      id: 3,
      name: "Регнус",
      sector: galaxySectors.morgon,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Регнус.svg",
    },
    90: {
      id: 4,
      name: "Мог",
      sector: galaxySectors.morgon,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Мог.svg",
    },
    91: {
      id: 3,
      name: "Вальмокс",
      sector: galaxySectors.rictus,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Вальмокс.svg",
    },
    92: {
      id: 4,
      name: "Иро",
      sector: galaxySectors.rictus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Иро.svg",
    },
    93: {
      id: 5,
      name: "Графмер",
      sector: galaxySectors.rictus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Графмер.svg",
    },
    94: {
      id: 1,
      name: "Новый Cтокгольм",
      sector: galaxySectors.hanzo,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Новый_Стокгольм.svg",
    },
    95: {
      id: 6,
      name: "Оазис",
      sector: galaxySectors.rictus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Оазис.svg",
    },
    96: {
      id: 7,
      name: "Генезис-прайм",
      sector: galaxySectors.rictus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Генезис-прайм.svg",
    },
    97: {
      id: 3,
      name: "Аванпост 32",
      sector: galaxySectors.saleria,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Аванпост_32.svg",
    },
    98: {
      id: 4,
      name: "Калипсо",
      sector: galaxySectors.saleria,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Калипсо.svg",
    },
    99: {
      id: 1,
      name: "Луга элизия",
      sector: galaxySectors.guang,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Луга_элизия.svg",
    },
    100: {
      id: 2,
      name: "Пещера альдеридж",
      sector: galaxySectors.guang,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Пещера_альдеридж.svg",
    },
    101: {
      id: 2,
      name: "Трандор",
      sector: galaxySectors.sten,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Трандор.svg",
    },
    102: {
      id: 1,
      name: "ВИТЗ",
      sector: galaxySectors.tarragon,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/ВИТЗ.svg",
    },
    103: {
      id: 3,
      name: "Хребет свободы",
      sector: galaxySectors.meridian,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Хребет_свободы.svg",
    },
    104: {
      id: 4,
      name: "Болдрик-прайм",
      sector: galaxySectors.meridian,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Болдрик-прайм.svg",
    },
    105: {
      id: 1,
      name: "Вир",
      sector: galaxySectors.theseus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Вир.svg",
    },
    106: {
      id: 2,
      name: "Купер",
      sector: galaxySectors.theseus,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Купер.svg",
    },
    107: {
      id: 2,
      name: "Станция «Осло»",
      sector: galaxySectors.sagan,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Станция_«Осло».svg",
    },
    108: {
      id: 1,
      name: "Пепли IX",
      sector: galaxySectors.xzar,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Пепли_IX.svg",
    },
    109: {
      id: 3,
      name: "Гюнвальд",
      sector: galaxySectors.sagan,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Гюнвальд.svg",
    },
    110: {
      id: 2,
      name: "Дольф",
      sector: galaxySectors.nanos,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Дольф.svg",
    },
    111: {
      id: 3,
      name: "Беквам III",
      sector: galaxySectors.nanos,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Беквам_III.svg",
    },
    112: {
      id: 4,
      name: "Дума тюр",
      sector: galaxySectors.nanos,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Дума_тюр.svg",
    },
    113: {
      id: 1,
      name: "Колодцы вернена",
      sector: galaxySectors.hydra,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Колодцы_Вернена.svg",
    },
    114: {
      id: 2,
      name: "Перевал асов",
      sector: galaxySectors.hydra,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Перевал_асов.svg",
    },
    115: {
      id: 1,
      name: "Залив авроры",
      sector: galaxySectors.valdis,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Залив_авроры.svg",
    },
    116: {
      id: 1,
      name: "Пента",
      sector: galaxySectors.lacaille,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Пента.svg",
    },
    117: {
      id: 4,
      name: "Елливаре",
      sector: galaxySectors.talus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Елливаре.svg",
    },
    118: {
      id: 1,
      name: "Вог-сойот",
      sector: galaxySectors.tanis,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Вог-сойот.svg",
    },
    119: {
      id: 2,
      name: "Киррик",
      sector: galaxySectors.arturion,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Киррик.svg",
    },
    120: {
      id: 3,
      name: "Мортакс-прайм",
      sector: galaxySectors.arturion,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Мортакс-прайм.svg",
    },
    121: {
      id: 4,
      name: "Станция «Уилфорд»",
      sector: galaxySectors.arturion,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Станция_«Уилфорд».svg",
    },
    122: {
      id: 5,
      name: "Первопроходец II",
      sector: galaxySectors.arturion,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Первопроходец_II.svg",
    },
    123: {
      id: 2,
      name: "Пески эрсона",
      sector: galaxySectors.falstaff,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Пески_эрсона.svg",
    },
    124: {
      id: 3,
      name: "Сокорро III",
      sector: galaxySectors.falstaff,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Сокорро_III.svg",
    },
    125: {
      id: 4,
      name: "Буровой камень",
      sector: galaxySectors.falstaff,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Буровой_камень.svg",
    },
    126: {
      id: 2,
      name: "Фенрир III",
      tidbit: `<p>Одна из четырех планет, где была развернута система терминального контроля (TCS) - сеть массивных башен, которые покрывают планету нейротоксином, известным как Терминцид. Установка этих башен TCS потребовала совместных усилий многих Адских Десантников и в конечном итоге привела к тому, что терминиды были удалены навсегда.</p>`,
      sector: galaxySectors.umlaut,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Фенрир_III.svg",
    },
    127: {
      id: 3,
      name: "Тьюринг",
      tidbit: `<p>Одна из четырех планет, где была развернута система терминального контроля (TCS) - сеть массивных башен, которые покрывают планету нейротоксином, известным как Терминцид. Установка этих башен TCS потребовала совместных усилий многих Адских Десантников и в конечном итоге привела к тому, что терминиды были удалены навсегда.</p>`,
      sector: galaxySectors.umlaut,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Тьюринг.svg",
    },
    128: {
      id: 7,
      name: "Ангельский риск",
      sector: galaxySectors.orion,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Ангельский_риск.svg",
    },
    129: {
      id: 2,
      name: "Дарий II",
      sector: galaxySectors.borgus,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Дарий_II.svg",
    },
    130: {
      id: 1,
      name: "Акамар IV",
      sector: galaxySectors.jinXi,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Акамар_IV.svg",
    },
    131: {
      id: 3,
      name: "Ахернар II",
      sector: galaxySectors.borgus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Ахернар_II.svg",
    },
    132: {
      id: 4,
      name: "Ахирд III",
      sector: galaxySectors.borgus,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Ахирд_III.svg",
    },
    133: {
      id: 2,
      name: "Акраб XI",
      sector: galaxySectors.ursa,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Акраб_XI.svg",
    },
    134: {
      id: 3,
      name: "Акрукс IX",
      sector: galaxySectors.ursa,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Акрукс_IX.svg",
    },
    135: {
      id: 4,
      name: "Акубенс-прайм",
      sector: galaxySectors.gallux,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Акубенс-прайм.svg",
    },
    136: {
      id: 5,
      name: "Эдхара",
      sector: galaxySectors.gallux,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Эдхара.svg",
    },
    137: {
      id: 6,
      name: "Афойя-бэй",
      sector: galaxySectors.gallux,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Афойя-бэй.svg",
    },
    138: {
      id: 2,
      name: "Айн-5",
      sector: galaxySectors.hanzo,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Айн-5.svg",
    },
    139: {
      id: 3,
      name: "Алаирт III",
      sector: galaxySectors.hanzo,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Алаирт_III.svg",
    },
    140: {
      id: 4,
      name: "Аламак VII",
      sector: galaxySectors.hanzo,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Аламак_VII.svg",
    },
    141: {
      id: 1,
      name: "Алараф",
      sector: galaxySectors.akira,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Алараф.svg",
    },
    142: {
      id: 2,
      name: "Алатфар XI",
      sector: galaxySectors.akira,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Алатфар_XI.svg",
    },
    143: {
      id: 3,
      name: "Эндар",
      sector: galaxySectors.akira,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Эндар.svg",
    },
    144: {
      id: 4,
      name: "Асперот-прайм",
      sector: galaxySectors.akira,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Асперот-прайм.svg",
    },
    145: {
      id: 3,
      name: "Беллатрикс",
      sector: galaxySectors.guang,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Беллатрикс.svg",
    },
    146: {
      id: 4,
      name: "Ботейн",
      sector: galaxySectors.guang,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Ботейн.svg",
    },
    147: {
      id: 2,
      name: "Осупсам",
      sector: galaxySectors.tarragon,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Осупсам.svg",
    },
    148: {
      id: 3,
      name: "Бринк-2",
      sector: galaxySectors.tarragon,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Бринк-2.svg",
    },
    149: {
      id: 4,
      name: "Бунда II",
      sector: galaxySectors.tarragon,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Бунда_II.svg",
    },
    150: {
      id: 5,
      name: "Канопус",
      sector: galaxySectors.tarragon,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Канопус.svg",
    },
    151: {
      id: 3,
      name: "Каф",
      sector: galaxySectors.theseus,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Каф.svg",
    },
    152: {
      id: 4,
      name: "Кастор",
      sector: galaxySectors.theseus,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Кастор.svg",
    },
    153: {
      id: 1,
      name: "Дирген",
      sector: galaxySectors.severin,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Дирген.svg",
    },
    154: {
      id: 2,
      name: "Дропнир",
      sector: galaxySectors.xzar,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Дропнир.svg",
    },
    155: {
      id: 3,
      name: "Морт",
      sector: galaxySectors.xzar,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Морт.svg",
    },
    156: {
      id: 4,
      name: "Ингмар",
      sector: galaxySectors.xzar,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Ингмар.svg",
    },
    157: {
      id: 1,
      name: "Чарбол-VII",
      sector: galaxySectors.andromeda,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Чарбол_VII.svg",
    },
    158: {
      id: 2,
      name: "Харон-прайм",
      sector: galaxySectors.andromeda,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Харон-прайм.svg",
    },
    159: {
      id: 1,
      name: "Хепесса IV",
      sector: galaxySectors.trigon,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Хепесса_IV.svg",
    },
    160: {
      id: 2,
      name: "Чухи",
      sector: galaxySectors.lacaille,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Чухи.svg",
    },
    161: {
      id: 3,
      name: "Хорт-бэй",
      sector: galaxySectors.lacaille,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Хорт-бэй.svg",
    },
    162: {
      id: 2,
      name: "Клаорелл",
      sector: galaxySectors.tanis,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Клаорелл.svg",
    },
    163: {
      id: 3,
      name: "Класа",
      sector: galaxySectors.tanis,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Класа.svg",
    },
    164: {
      id: 4,
      name: "Демиург",
      sector: galaxySectors.tanis,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Демиург.svg",
    },
    165: {
      id: 6,
      name: "Денеб II",
      sector: galaxySectors.arturion,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Денеб_II.svg",
    },
    166: {
      id: 7,
      name: "Электра-бэй",
      sector: galaxySectors.arturion,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Электра-бэй.svg",
    },
    167: {
      id: 1,
      name: "Энулиале",
      sector: galaxySectors.lestrade,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Энулиале.svg",
    },
    168: {
      id: 2,
      name: "Эпсилон-финсис VI",
      sector: galaxySectors.lestrade,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Эпсилон-финсис_VI.svg",
    },
    169: {
      id: 4,
      name: "Эрата-прайм",
      tidbit: `<p>Одна из четырех планет, где была развернута система терминального контроля (TCS) - сеть массивных башен, которые покрывают планету нейротоксином, известным как Терминцид. Установка этих башен TCS потребовала совместных усилий многих Адских Десантников и в конечном итоге привела к тому, что терминиды были удалены навсегда.</p>`,
      sector: galaxySectors.umlaut,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Эрата-прайм.svg",
    },
    170: {
      id: 2,
      name: "Эстану",
      sector: galaxySectors.draco,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Эстану.svg",
    },
    171: {
      id: 3,
      name: "Фори-прайм",
      sector: galaxySectors.draco,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Фори-прайм.svg",
    },
    172: {
      id: 2,
      name: "Гакрукс",
      sector: galaxySectors.jinXi,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Гакрукс.svg",
    },
    173: {
      id: 3,
      name: "Гар-харен",
      sector: galaxySectors.jinXi,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Гар-харен.svg",
    },
    174: {
      id: 4,
      name: "Гатрия",
      sector: galaxySectors.jinXi,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Гатрия.svg",
    },
    175: {
      id: 4,
      name: "Гемма",
      sector: galaxySectors.ursa,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Гемма.svg",
    },
    176: {
      id: 1,
      name: "Гранд Эррант",
      sector: galaxySectors.farsight,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Гранд_Эррант.svg",
    },
    177: {
      id: 2,
      name: "Хадар",
      sector: galaxySectors.ferris,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Хадар.svg",
    },
    178: {
      id: 1,
      name: "Хака",
      sector: galaxySectors.leo,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Хака.svg",
    },
    179: {
      id: 3,
      name: "Хальдус",
      sector: galaxySectors.ferris,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Хальдус.svg",
    },
    180: {
      id: 2,
      name: "Порт-галье",
      sector: galaxySectors.leo,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Порт-галье.svg",
    },
    181: {
      id: 4,
      name: "Хартон II",
      sector: galaxySectors.ferris,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Хартон_II.svg",
    },
    182: {
      id: 1,
      name: "Хесоэ-прайм",
      sector: galaxySectors.rigel,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Хесоэ-прайм.svg",
    },
    183: {
      id: 5,
      name: "Хезе-бэй",
      sector: galaxySectors.hanzo,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Хезе-бэй.svg",
    },
    184: {
      id: 2,
      name: "Хорт",
      sector: galaxySectors.rigel,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Хорт.svg",
    },
    185: {
      id: 1,
      name: "Гидробиус",
      sector: galaxySectors.omega,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Гидробиус.svg",
    },
    186: {
      id: 2,
      name: "Карлия",
      sector: galaxySectors.omega,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Карлия.svg",
    },
    187: {
      id: 5,
      name: "Кейд",
      sector: galaxySectors.akira,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Кейд.svg",
    },
    188: {
      id: 5,
      name: "Хандарк",
      sector: galaxySectors.guang,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Хандарк.svg",
    },
    189: {
      id: 1,
      name: "Клака 5",
      sector: galaxySectors.alstrad,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Клака_5.svg",
    },
    190: {
      id: 2,
      name: "Порт-кнет",
      sector: galaxySectors.alstrad,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Порт-кнет.svg",
    },
    191: {
      id: 3,
      name: "Краз",
      sector: galaxySectors.alstrad,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Краз.svg",
    },
    192: {
      id: 1,
      name: "Кума",
      sector: galaxySectors.hawking,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Кума.svg",
    },
    193: {
      id: 5,
      name: "Ластоф",
      sector: galaxySectors.theseus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Ластоф.svg",
    },
    194: {
      id: 1,
      name: "Ленг II",
      sector: galaxySectors.quintus,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Ленг_II.svg",
    },
    195: {
      id: 4,
      name: "Лесат",
      sector: galaxySectors.lacaille,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Лесат.svg",
    },
    196: {
      id: 2,
      name: "Майя",
      sector: galaxySectors.severin,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Майя.svg",
    },
    197: {
      id: 3,
      name: "Малевелон-крик",
      sector: galaxySectors.severin,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Малевелон_крик.svg",
    },
    198: {
      id: 5,
      name: "Мантес",
      sector: galaxySectors.xzar,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Мантес.svg",
    },
    199: {
      id: 3,
      name: "Марфарк",
      sector: galaxySectors.andromeda,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Марфарк.svg",
    },
    200: {
      id: 4,
      name: "Мартале",
      sector: galaxySectors.andromeda,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Мартале.svg",
    },
    201: {
      id: 5,
      name: "Матар-бэй",
      sector: galaxySectors.andromeda,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Матар-бэй.svg",
    },
    202: {
      id: 1,
      name: "Мейсса",
      sector: galaxySectors.ymir,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Мейсса.svg",
    },
    203: {
      id: 2,
      name: "Мекбуда",
      sector: galaxySectors.valdis,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Мекбуда.svg",
    },
    204: {
      id: 3,
      name: "Менкент",
      sector: galaxySectors.hydra,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Менкент.svg",
    },
    205: {
      id: 3,
      name: "Мерак",
      sector: galaxySectors.valdis,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Мерак.svg",
    },
    206: {
      id: 4,
      name: "Марга IV",
      sector: galaxySectors.valdis,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Марга_IV.svg",
    },
    207: {
      id: 2,
      name: "Минхир",
      sector: galaxySectors.gellert,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Минхир.svg",
    },
    208: {
      id: 3,
      name: "Минтория",
      sector: galaxySectors.gellert,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Минтория.svg",
    },
    209: {
      id: 2,
      name: "Мордия-9",
      sector: galaxySectors.hawking,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Мордия-9.svg",
    },
    210: {
      id: 3,
      name: "Нанбатея II",
      sector: galaxySectors.lestrade,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Нанбатея_II.svg",
    },
    211: {
      id: 4,
      name: "Нави VII",
      sector: galaxySectors.lestrade,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Нави_VII.svg",
    },
    212: {
      id: 2,
      name: "Нивель 43",
      sector: galaxySectors.mirin,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Нивель_43.svg",
    },
    213: {
      id: 3,
      name: "Ошоне",
      imageCount: 2,
      sector: galaxySectors.mirin,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Ошоне.svg",
    },
    214: {
      id: 3,
      name: "Оверго-прайм",
      sector: galaxySectors.sten,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Оверго-прайм.svg",
    },
    215: {
      id: 5,
      name: "Пандион XXIV",
      sector: galaxySectors.jinXi,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Пандион_XXIV.svg",
    },
    216: {
      id: 4,
      name: "Партион",
      sector: galaxySectors.sten,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Партион.svg",
    },
    217: {
      id: 5,
      name: "Пикок",
      sector: galaxySectors.sten,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Пикок.svg",
    },
    218: {
      id: 6,
      name: "Факт-бэй",
      sector: galaxySectors.jinXi,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Факт-бэй.svg",
    },
    219: {
      id: 2,
      name: "Феркад II",
      sector: galaxySectors.farsight,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Феркад_II.svg",
    },
    220: {
      id: 3,
      name: "Полярис-прайм",
      sector: galaxySectors.farsight,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Полярис-прайм.svg",
    },
    221: {
      id: 4,
      name: "Поллукс-31",
      sector: galaxySectors.farsight,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Поллукс-31.svg",
    },
    222: {
      id: 5,
      name: "Праса",
      sector: galaxySectors.farsight,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Праса.svg",
    },
    223: {
      id: 3,
      name: "Пропус",
      sector: galaxySectors.leo,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Пропус.svg",
    },
    224: {
      id: 4,
      name: "Рас-альгети",
      sector: galaxySectors.leo,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Рас-альгети.svg",
    },
    225: {
      id: 3,
      name: "Арди-4",
      sector: galaxySectors.rigel,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Арди-4.svg",
    },
    226: {
      id: 4,
      name: "Роуг 5",
      sector: galaxySectors.rigel,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Роуг_5.svg",
    },
    227: {
      id: 5,
      name: "Рирга-бэй",
      sector: galaxySectors.rigel,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Рирга-бэй.svg",
    },
    228: {
      id: 3,
      name: "Сиэсс",
      sector: galaxySectors.omega,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Сиэсс.svg",
    },
    229: {
      id: 4,
      name: "Сенже-23",
      sector: galaxySectors.omega,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
      image: "/static/GalaxyMap/planets/Сиэсс.svg",
    },
    230: {
      id: 5,
      name: "Сетия",
      sector: galaxySectors.omega,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Сетия.svg",
    },
    231: {
      id: 1,
      name: "Шете",
      sector: galaxySectors.xiTauri,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Шете.svg",
    },
    232: {
      id: 2,
      name: "Симнот",
      sector: galaxySectors.xiTauri,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Симнот.svg",
    },
    233: {
      id: 3,
      name: "Сириус",
      sector: galaxySectors.xiTauri,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Сириус.svg",
    },
    234: {
      id: 4,
      name: "Скат-бэй",
      sector: galaxySectors.xiTauri,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Скат-бэй.svg",
    },
    235: {
      id: 2,
      name: "Сферион",
      sector: galaxySectors.quintus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Сферион.svg",
    },
    236: {
      id: 3,
      name: "Стор та-прайм",
      sector: galaxySectors.quintus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Стор_та-прайм.svg",
    },
    237: {
      id: 4,
      name: "Стаут",
      sector: galaxySectors.quintus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Стаут.svg",
    },
    238: {
      id: 5,
      name: "Термодон",
      sector: galaxySectors.quintus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Термодон.svg",
    },
    239: {
      id: 4,
      name: "Тибит",
      sector: galaxySectors.severin,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Тибит.svg",
    },
    240: {
      id: 6,
      name: "Тьен-кван",
      tidbit: `
      <p>Тьен-кван - гордый дом знаменитого Моргантонского арсенала, где куют лучшие экзоскелеты! Эти ультрасовременные чудеса были на грани развертывания по всей галактике, пока не налетели эти надоедливые автоматоны, пытаясь забрать то, что принадлежит нам. Но демократия снова восторжествовала, поскольку наши отважные Адские Десантники быстро приступили к действиям, чтобы защитить эту сокровищницу технологий.</p>
      <p>Автоматоны, не подозревавшие о прекрасной возможности, на которую они наткнулись, были быстро уничтожены благодаря молниеносной реакции наших элитных сил. Верховное командование Супер-Земли издало коллективный вздох облегчения, когда 8 марта был освобожден Тьен-кван, обеспечив будущее экзоскелетов EXO-45 Patriot и обеспечив их немедленную доступность для реквизиции нашими доблестными войсками. Еще одна победа Супер-Земли, благодаря непоколебимому мужеству наших Адских Десантников!</p>
    `,
      sector: galaxySectors.theseus,
      biome: biomes.iceMossSpecial,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Тьен-кван.svg",
    },
    241: {
      id: 2,
      name: "Труст",
      sector: galaxySectors.trigon,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
      image: "/static/GalaxyMap/planets/Труст.svg",
    },
    242: {
      id: 5,
      name: "Убанея",
      sector: galaxySectors.severin,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Убанея.svg",
    },
    243: {
      id: 3,
      name: "Устоту",
      sector: galaxySectors.trigon,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
      image: "/static/GalaxyMap/planets/Устоту.svg",
    },
    244: {
      id: 4,
      name: "Вандалон IV",
      sector: galaxySectors.trigon,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Вандалон_IV.svg",
    },
    245: {
      id: 5,
      name: "Верилия-5",
      sector: galaxySectors.trigon,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Верилия-5.svg",
    },
    246: {
      id: 2,
      name: "Васат",
      sector: galaxySectors.ymir,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
      image: "/static/GalaxyMap/planets/Васат.svg",
    },
    247: {
      id: 3,
      name: "Вега-бэй",
      sector: galaxySectors.ymir,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
      image: "/static/GalaxyMap/planets/Вега-бэй.svg",
    },
    248: {
      id: 4,
      name: "Везен",
      sector: galaxySectors.ymir,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
      image: "/static/GalaxyMap/planets/Везен.svg",
    },
    249: {
      id: 5,
      name: "Виндемитарикс-прайм",
      sector: galaxySectors.valdis,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Виндемитарикс-прайм.svg",
    },
    250: {
      id: 5,
      name: "Экс-45",
      sector: galaxySectors.ymir,
      biome: biomes.newJungle,
      weatherConditions: [weatherConditions.rainstorms],
      image: "/static/GalaxyMap/planets/Экс-45.svg",
    },
    251: {
      id: 5,
      name: "Йед-приор",
      sector: galaxySectors.tanis,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
      image: "/static/GalaxyMap/planets/Йед-приор.svg",
    },
    252: {
      id: 6,
      name: "Зефия",
      sector: galaxySectors.tanis,
      biome: biomes.ethereal,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Зефия.svg",
    },
    253: {
      id: 4,
      name: "Зосма",
      sector: galaxySectors.gellert,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Зосма.svg",
    },
    254: {
      id: 5,
      name: "Зания-прайм",
      sector: galaxySectors.gellert,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Зания-прайм.svg",
    },
    255: {
      id: 3,
      name: "Скиттер",
      sector: galaxySectors.hawking,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Скиттер.svg",
    },
    256: {
      id: 4,
      name: "Эйфория III",
      sector: galaxySectors.hawking,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
      image: "/static/GalaxyMap/planets/Эйфория_III.svg",
    },
    257: {
      id: 5,
      name: "Диаспора X",
      sector: galaxySectors.lestrade,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Диаспора_X.svg",
    },
    258: {
      id: 6,
      name: "Самоцветные утесы",
      sector: galaxySectors.lestrade,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
      image: "/static/GalaxyMap/planets/Самоцветные_утесы.svg",
    },
    259: {
      id: 4,
      name: "Загон-прайм",
      sector: galaxySectors.mirin,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
      image: "/static/GalaxyMap/planets/Загон-прайм.svg",
    },
    260: {
      id: 7,
      name: "Омикрон",
      sector: galaxySectors.lestrade,
      biome: biomes.tundra,
      weatherConditions: [],
      image: "/static/GalaxyMap/planets/Омикрон.svg",
    },
    261: {
      id: 6,
      name: "Киберстан",
      sector: galaxySectors.valdis,
      biome: biomes.cyberstan,
      weatherConditions: [weatherConditions.extremeCold],
      image: "/static/GalaxyMap/planets/Киберстан.svg",
    },
  };

  constructor() {
    makeAutoObservable(this);
  }

  changeCurrentPlanetInfo(id: number, sector: any) {
    this.currentPlanetInfo = { id: id, sector: sector };
  }

  clearCurrentPlanetInfo() {
    this.currentPlanetInfo = {} as CurrentPlanetInfo;
  }
}

export const planetsStore = new PlanetsStore();
