import { makeAutoObservable } from "mobx";

import { galaxySectors } from "@/data/galaxySectors";
import { weatherConditions } from "@/data/planetWeatherConditions";
import { biomes } from "@/data/planetBiomes";

import { CurrentPlanetInfo } from "@/utils/storeInterfaces";

class PlanetsStore {
  currentPlanetInfo = {} as CurrentPlanetInfo;

  planets = {
    0: {
      id: 1,
      name: "Супер-Земля",
      sector: galaxySectors.sol,
      biome: biomes.superEarth,
      weatherConditions: [],
    },
    1: {
      id: 2,
      name: "Марс",
      sector: galaxySectors.sol,
      biome: null,
      weatherConditions: [],
    },
    2: {
      id: 1,
      name: "Клен Дахт II",
      sector: galaxySectors.altus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    3: {
      id: 2,
      name: "Следопыт V",
      sector: galaxySectors.altus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    4: {
      id: 3,
      name: "Вдовья гавань",
      sector: galaxySectors.altus,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    5: {
      id: 4,
      name: "Новая гавань",
      sector: galaxySectors.altus,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    6: {
      id: 5,
      name: "Пилен V",
      sector: galaxySectors.altus,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    7: {
      id: 1,
      name: "Гидропад прайм",
      sector: galaxySectors.barnard,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    8: {
      id: 1,
      name: "Зея ругозия",
      sector: galaxySectors.ferris,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    9: {
      id: 2,
      name: "Дерроуспорт",
      sector: galaxySectors.barnard,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    10: {
      id: 3,
      name: "Форнскогур II",
      sector: galaxySectors.barnard,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    11: {
      id: 4,
      name: "Мидасбург",
      sector: galaxySectors.barnard,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    12: {
      id: 1,
      name: "Цербер IIIc",
      sector: galaxySectors.cancri,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    13: {
      id: 2,
      name: "Водопады процветания",
      sector: galaxySectors.cancri,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    14: {
      id: 1,
      name: "Окул VI",
      sector: galaxySectors.gothmar,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    15: {
      id: 1,
      name: "Залив мучеников",
      sector: galaxySectors.cantolus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    16: {
      id: 2,
      name: "Пик свободы",
      sector: galaxySectors.cantolus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    17: {
      id: 1,
      name: "Форт единения",
      sector: galaxySectors.orion,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    18: {
      id: 3,
      name: "Кельвинор",
      sector: galaxySectors.cantolus,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    19: {
      id: 1,
      name: "Призрак",
      sector: galaxySectors.idun,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    20: {
      id: 1,
      name: "Игла",
      sector: galaxySectors.kelvin,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    21: {
      id: 2,
      name: "Новая кируна",
      sector: galaxySectors.kelvin,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    22: {
      id: 3,
      name: "Форт правосудия",
      sector: galaxySectors.kelvin,
      biome: null,
      weatherConditions: [],
    },
    23: {
      id: 4,
      name: "Зегемский рай",
      sector: galaxySectors.kelvin,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    24: {
      id: 1,
      name: "Провидение",
      sector: galaxySectors.iptus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    25: {
      id: 2,
      name: "Примортия",
      sector: galaxySectors.iptus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    26: {
      id: 1,
      name: "Сульфура",
      sector: galaxySectors.celeste,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    27: {
      id: 2,
      name: "Нублария I",
      sector: galaxySectors.celeste,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    28: {
      id: 3,
      name: "Кракату",
      sector: galaxySectors.celeste,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    29: {
      id: 1,
      name: "Вольтерра",
      sector: galaxySectors.korpus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    30: {
      id: 2,
      name: "Горн",
      sector: galaxySectors.korpus,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    31: {
      id: 5,
      name: "Вуаль",
      sector: galaxySectors.barnard,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    32: {
      id: 6,
      name: "Марр IV",
      sector: galaxySectors.barnard,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    33: {
      id: 3,
      name: "Форт безопасности",
      sector: galaxySectors.cancri,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    34: {
      id: 4,
      name: "Сейшельский пляж",
      sector: galaxySectors.cancri,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    35: {
      id: 1,
      name: "Хеллмейр",
      imageCount: 3,
      sector: galaxySectors.mirin,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    36: {
      id: 5,
      name: "Эффлувия",
      sector: galaxySectors.cancri,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    37: {
      id: 2,
      name: "Солгаст",
      sector: galaxySectors.gothmar,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    38: {
      id: 3,
      name: "Дилувия",
      sector: galaxySectors.gothmar,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    39: {
      id: 4,
      name: "Виридия-прайм",
      sector: galaxySectors.cantolus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    40: {
      id: 5,
      name: "Обари",
      sector: galaxySectors.cantolus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    41: {
      id: 2,
      name: "Мирадеш",
      sector: galaxySectors.idun,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    42: {
      id: 3,
      name: "Атрама",
      sector: galaxySectors.idun,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    43: {
      id: 5,
      name: "Эмерия",
      sector: galaxySectors.kelvin,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    44: {
      id: 1,
      name: "Барабос",
      sector: galaxySectors.marspira,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    45: {
      id: 2,
      name: "Фенмейр",
      sector: galaxySectors.marspira,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    46: {
      id: 3,
      name: "Мастия",
      sector: galaxySectors.marspira,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    47: {
      id: 1,
      name: "Шаллус",
      sector: galaxySectors.talus,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    48: {
      id: 3,
      name: "Кракабос",
      sector: galaxySectors.iptus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    49: {
      id: 4,
      name: "Иридика",
      sector: galaxySectors.iptus,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    50: {
      id: 2,
      name: "Астерра",
      sector: galaxySectors.orion,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    51: {
      id: 1,
      name: "Азур II",
      sector: galaxySectors.sten,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    52: {
      id: 4,
      name: "Айвис",
      sector: galaxySectors.celeste,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    53: {
      id: 5,
      name: "Слиф",
      sector: galaxySectors.celeste,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    54: {
      id: 3,
      name: "Карамур",
      sector: galaxySectors.korpus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    55: {
      id: 1,
      name: "Кхарст",
      sector: galaxySectors.gallux,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    56: {
      id: 1,
      name: "Юкория",
      sector: galaxySectors.morgon,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    57: {
      id: 2,
      name: "Мириум",
      sector: galaxySectors.morgon,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    58: {
      id: 1,
      name: "Керт II",
      sector: galaxySectors.rictus,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    59: {
      id: 2,
      name: "Парш",
      sector: galaxySectors.rictus,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    60: {
      id: 1,
      name: "Риф",
      sector: galaxySectors.saleria,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    61: {
      id: 2,
      name: "Ирулта",
      sector: galaxySectors.saleria,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    62: {
      id: 1,
      name: "Эморат",
      sector: galaxySectors.meridian,
      biome: null,
      weatherConditions: [],
    },
    63: {
      id: 2,
      name: "Илдуна-прайм",
      sector: galaxySectors.meridian,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    64: {
      id: 4,
      name: "Утроба",
      sector: galaxySectors.idun,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    65: {
      id: 1,
      name: "Меридия",
      tidbit: `<p>Одна из четырех планет, где была развернута система терминального контроля (TCS) - сеть массивных башен, которые покрывают планету нейротоксином, известным как Терминцид. Установка этих башен TCS потребовала совместных усилий многих Адских Десантников и в конечном итоге привела к тому, что терминиды были удалены навсегда.</p>`,
      sector: galaxySectors.umlaut,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    66: {
      id: 1,
      name: "Борея",
      sector: galaxySectors.sagan,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    67: {
      id: 4,
      name: "Курия",
      sector: galaxySectors.marspira,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    68: {
      id: 5,
      name: "Тарш",
      sector: galaxySectors.marspira,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    69: {
      id: 2,
      name: "Шелт",
      sector: galaxySectors.talus,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    70: {
      id: 3,
      name: "Имбер",
      sector: galaxySectors.talus,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    71: {
      id: 1,
      name: "Блистика",
      sector: galaxySectors.gellert,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    72: {
      id: 5,
      name: "Ратч",
      sector: galaxySectors.iptus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    73: {
      id: 1,
      name: "Юльхейм",
      sector: galaxySectors.nanos,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    74: {
      id: 6,
      name: "Валгаард",
      sector: galaxySectors.iptus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    75: {
      id: 1,
      name: "Арктур",
      sector: galaxySectors.arturion,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    76: {
      id: 1,
      name: "Эскер",
      sector: galaxySectors.falstaff,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    77: {
      id: 3,
      name: "Терек",
      sector: galaxySectors.orion,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    78: {
      id: 4,
      name: "Сиррус",
      sector: galaxySectors.orion,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    79: {
      id: 1,
      name: "Кримсика",
      imageCount: 3,
      sector: galaxySectors.draco,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    80: {
      id: 5,
      name: "Хиит",
      sector: galaxySectors.orion,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    81: {
      id: 6,
      name: "Вельд",
      sector: galaxySectors.orion,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    82: {
      id: 4,
      name: "Альта V",
      sector: galaxySectors.korpus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    83: {
      id: 1,
      name: "Урсика XI",
      sector: galaxySectors.borgus,
      biome: null,
      weatherConditions: [],
    },
    84: {
      id: 5,
      name: "Инари",
      sector: galaxySectors.korpus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    85: {
      id: 1,
      name: "Скааш",
      sector: galaxySectors.ursa,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    86: {
      id: 6,
      name: "Морадеш",
      sector: galaxySectors.celeste,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    87: {
      id: 2,
      name: "Расп",
      sector: galaxySectors.gallux,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    88: {
      id: 3,
      name: "Башир",
      sector: galaxySectors.gallux,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    89: {
      id: 3,
      name: "Регнус",
      sector: galaxySectors.morgon,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    90: {
      id: 4,
      name: "Мог",
      sector: galaxySectors.morgon,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    91: {
      id: 3,
      name: "Вальмокс",
      sector: galaxySectors.rictus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    92: {
      id: 4,
      name: "Иро",
      sector: galaxySectors.rictus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    93: {
      id: 5,
      name: "Графмер",
      sector: galaxySectors.rictus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    94: {
      id: 1,
      name: "Новый стокгольм",
      sector: galaxySectors.hanzo,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    95: {
      id: 6,
      name: "Оазис",
      sector: galaxySectors.rictus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    96: {
      id: 7,
      name: "Генезис-прайм",
      sector: galaxySectors.rictus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    97: {
      id: 3,
      name: "Аванпост 32",
      sector: galaxySectors.saleria,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    98: {
      id: 4,
      name: "Калипсо",
      sector: galaxySectors.saleria,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    99: {
      id: 1,
      name: "Луга элизия",
      sector: galaxySectors.guang,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    100: {
      id: 2,
      name: "Пещера альдеридж",
      sector: galaxySectors.guang,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    101: {
      id: 2,
      name: "Трандор",
      sector: galaxySectors.sten,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    102: {
      id: 1,
      name: "Восточный иридиевый торговый залив",
      sector: galaxySectors.tarragon,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    103: {
      id: 3,
      name: "Хребет свободы",
      sector: galaxySectors.meridian,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    104: {
      id: 4,
      name: "Болдрик-прайм",
      sector: galaxySectors.meridian,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    105: {
      id: 1,
      name: "Вир",
      sector: galaxySectors.theseus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    106: {
      id: 2,
      name: "Купер",
      sector: galaxySectors.theseus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    107: {
      id: 2,
      name: "Станция «Осло»",
      sector: galaxySectors.sagan,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    108: {
      id: 1,
      name: "Пепли IX",
      sector: galaxySectors.xzar,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    109: {
      id: 3,
      name: "Гюнвальд",
      sector: galaxySectors.sagan,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    110: {
      id: 2,
      name: "Дольф",
      sector: galaxySectors.nanos,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    111: {
      id: 3,
      name: "Беквам III",
      sector: galaxySectors.nanos,
      biome: null,
      weatherConditions: [],
    },
    112: {
      id: 4,
      name: "Дума тюр",
      sector: galaxySectors.nanos,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    113: {
      id: 1,
      name: "Колодцы вернена",
      sector: galaxySectors.hydra,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    114: {
      id: 2,
      name: "Перевал асов",
      sector: galaxySectors.hydra,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    115: {
      id: 1,
      name: "Залив авроры",
      sector: galaxySectors.valdis,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    116: {
      id: 1,
      name: "Пента",
      sector: galaxySectors.lacaille,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    117: {
      id: 4,
      name: "Елливаре",
      sector: galaxySectors.talus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    118: {
      id: 1,
      name: "Вог-сойот",
      sector: galaxySectors.tanis,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    119: {
      id: 2,
      name: "Киррик",
      sector: galaxySectors.arturion,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    120: {
      id: 3,
      name: "Мортакс-прайм",
      sector: galaxySectors.arturion,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    121: {
      id: 4,
      name: "Станция «Уилфорд»",
      sector: galaxySectors.arturion,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    122: {
      id: 5,
      name: "Первопроходец II",
      sector: galaxySectors.arturion,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    123: {
      id: 2,
      name: "Пески эрсона",
      sector: galaxySectors.falstaff,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    124: {
      id: 3,
      name: "Сокорро III",
      sector: galaxySectors.falstaff,
      biome: null,
      weatherConditions: [],
    },
    125: {
      id: 4,
      name: "Буровой камень",
      sector: galaxySectors.falstaff,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    126: {
      id: 2,
      name: "Фенрир III",
      tidbit: `<p>Одна из четырех планет, где была развернута система терминального контроля (TCS) - сеть массивных башен, которые покрывают планету нейротоксином, известным как Терминцид. Установка этих башен TCS потребовала совместных усилий многих Адских Десантников и в конечном итоге привела к тому, что терминиды были удалены навсегда.</p>`,
      sector: galaxySectors.umlaut,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    127: {
      id: 3,
      name: "Тьюринг",
      tidbit: `<p>Одна из четырех планет, где была развернута система терминального контроля (TCS) - сеть массивных башен, которые покрывают планету нейротоксином, известным как Терминцид. Установка этих башен TCS потребовала совместных усилий многих Адских Десантников и в конечном итоге привела к тому, что терминиды были удалены навсегда.</p>`,
      sector: galaxySectors.umlaut,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    128: {
      id: 7,
      name: "Ангельский риск",
      sector: galaxySectors.orion,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    129: {
      id: 2,
      name: "Дарий II",
      sector: galaxySectors.borgus,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    130: {
      id: 1,
      name: "Акамар IV",
      sector: galaxySectors.jinXi,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    131: {
      id: 3,
      name: "Ахернар II",
      sector: galaxySectors.borgus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    132: {
      id: 4,
      name: "Ахирд III",
      sector: galaxySectors.borgus,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    133: {
      id: 2,
      name: "Акраб XI",
      sector: galaxySectors.ursa,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    134: {
      id: 3,
      name: "Акрукс IX",
      sector: galaxySectors.ursa,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    135: {
      id: 4,
      name: "Акубенс-прайм",
      sector: galaxySectors.gallux,
      biome: null,
      weatherConditions: [],
    },
    136: {
      id: 5,
      name: "Эдхара",
      sector: galaxySectors.gallux,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    137: {
      id: 6,
      name: "Афойя-бэй",
      sector: galaxySectors.gallux,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    138: {
      id: 2,
      name: "Айн-5",
      sector: galaxySectors.hanzo,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    139: {
      id: 3,
      name: "Алаирт III",
      sector: galaxySectors.hanzo,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    140: {
      id: 4,
      name: "Аламак VII",
      sector: galaxySectors.hanzo,
      biome: null,
      weatherConditions: [],
    },
    141: {
      id: 1,
      name: "Алараф",
      sector: galaxySectors.akira,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    142: {
      id: 2,
      name: "Алатфар XI",
      sector: galaxySectors.akira,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    143: {
      id: 3,
      name: "Эндар",
      sector: galaxySectors.akira,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    144: {
      id: 4,
      name: "Асперот-прайм",
      sector: galaxySectors.akira,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    145: {
      id: 3,
      name: "Беллатрикс",
      sector: galaxySectors.guang,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    146: {
      id: 4,
      name: "Ботейн",
      sector: galaxySectors.guang,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    147: {
      id: 2,
      name: "Осупсам",
      sector: galaxySectors.tarragon,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    148: {
      id: 3,
      name: "Бринк-2",
      sector: galaxySectors.tarragon,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    149: {
      id: 4,
      name: "Бунда II",
      sector: galaxySectors.tarragon,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    150: {
      id: 5,
      name: "Канопус",
      sector: galaxySectors.tarragon,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    151: {
      id: 3,
      name: "Каф",
      sector: galaxySectors.theseus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    152: {
      id: 4,
      name: "Кастор",
      sector: galaxySectors.theseus,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    153: {
      id: 1,
      name: "Дирген",
      sector: galaxySectors.severin,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    154: {
      id: 2,
      name: "Дропнир",
      sector: galaxySectors.xzar,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    155: {
      id: 3,
      name: "Морт",
      sector: galaxySectors.xzar,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    156: {
      id: 4,
      name: "Ингмар",
      sector: galaxySectors.xzar,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    157: {
      id: 1,
      name: "Чарбол-VII",
      sector: galaxySectors.andromeda,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    158: {
      id: 2,
      name: "Харон-прайм",
      sector: galaxySectors.andromeda,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    159: {
      id: 1,
      name: "Хепесса IV",
      sector: galaxySectors.trigon,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    160: {
      id: 2,
      name: "Чухи",
      sector: galaxySectors.lacaille,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    161: {
      id: 3,
      name: "Хорт-бэй",
      sector: galaxySectors.lacaille,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    162: {
      id: 2,
      name: "Клаорелл",
      sector: galaxySectors.tanis,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    163: {
      id: 3,
      name: "Класа",
      sector: galaxySectors.tanis,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    164: {
      id: 4,
      name: "Демиург",
      sector: galaxySectors.tanis,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    165: {
      id: 6,
      name: "Денеб II",
      sector: galaxySectors.arturion,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    166: {
      id: 7,
      name: "Электра-бэй",
      sector: galaxySectors.arturion,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    167: {
      id: 1,
      name: "Энулиале",
      sector: galaxySectors.lestrade,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    168: {
      id: 2,
      name: "Эпсилон-финсис VI",
      sector: galaxySectors.lestrade,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    169: {
      id: 4,
      name: "Эрата-прайм",
      tidbit: `<p>Одна из четырех планет, где была развернута система терминального контроля (TCS) - сеть массивных башен, которые покрывают планету нейротоксином, известным как Терминцид. Установка этих башен TCS потребовала совместных усилий многих Адских Десантников и в конечном итоге привела к тому, что терминиды были удалены навсегда.</p>`,
      sector: galaxySectors.umlaut,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    170: {
      id: 2,
      name: "Эстану",
      sector: galaxySectors.draco,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    171: {
      id: 3,
      name: "Фори-прайм",
      sector: galaxySectors.draco,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    172: {
      id: 2,
      name: "Гакрукс",
      sector: galaxySectors.jinXi,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    173: {
      id: 3,
      name: "Гар-харен",
      sector: galaxySectors.jinXi,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    174: {
      id: 4,
      name: "Гатрия",
      sector: galaxySectors.jinXi,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    175: {
      id: 4,
      name: "Гемма",
      sector: galaxySectors.ursa,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    176: {
      id: 1,
      name: "Гранд Эррант",
      sector: galaxySectors.farsight,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    177: {
      id: 2,
      name: "Хадар",
      sector: galaxySectors.ferris,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    178: {
      id: 1,
      name: "Хака",
      sector: galaxySectors.leo,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    179: {
      id: 3,
      name: "Хальдус",
      sector: galaxySectors.ferris,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    180: {
      id: 2,
      name: "Порт-галье",
      sector: galaxySectors.leo,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    181: {
      id: 4,
      name: "Хартон II",
      sector: galaxySectors.ferris,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    182: {
      id: 1,
      name: "Хесоэ-прайм",
      sector: galaxySectors.rigel,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    183: {
      id: 5,
      name: "Хезе-бэй",
      sector: galaxySectors.hanzo,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    184: {
      id: 2,
      name: "Хорт",
      sector: galaxySectors.rigel,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    185: {
      id: 1,
      name: "Гидробиус",
      sector: galaxySectors.omega,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    186: {
      id: 2,
      name: "Карлия",
      sector: galaxySectors.omega,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    187: {
      id: 5,
      name: "Кейд",
      sector: galaxySectors.akira,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    188: {
      id: 5,
      name: "Хандарк",
      sector: galaxySectors.guang,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    189: {
      id: 1,
      name: "Клака 5",
      sector: galaxySectors.alstrad,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    190: {
      id: 2,
      name: "Порт-кнет",
      sector: galaxySectors.alstrad,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    191: {
      id: 3,
      name: "Краз",
      sector: galaxySectors.alstrad,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    192: {
      id: 1,
      name: "Кума",
      sector: galaxySectors.hawking,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    193: {
      id: 5,
      name: "Ластоф",
      sector: galaxySectors.theseus,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    194: {
      id: 1,
      name: "Ленг II",
      sector: galaxySectors.quintus,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    195: {
      id: 4,
      name: "Лесат",
      sector: galaxySectors.lacaille,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    196: {
      id: 2,
      name: "Майя",
      sector: galaxySectors.severin,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    197: {
      id: 3,
      name: "Малевелон-крик",
      sector: galaxySectors.severin,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    198: {
      id: 5,
      name: "Мантес",
      sector: galaxySectors.xzar,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    199: {
      id: 3,
      name: "Марфарк",
      sector: galaxySectors.andromeda,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    200: {
      id: 4,
      name: "Мартале",
      sector: galaxySectors.andromeda,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    201: {
      id: 5,
      name: "Матар-бэй",
      sector: galaxySectors.andromeda,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    202: {
      id: 1,
      name: "Мейсса",
      sector: galaxySectors.ymir,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    203: {
      id: 2,
      name: "Мекбуда",
      sector: galaxySectors.valdis,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    204: {
      id: 3,
      name: "Менкент",
      sector: galaxySectors.hydra,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    205: {
      id: 3,
      name: "Мерак",
      sector: galaxySectors.valdis,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    206: {
      id: 4,
      name: "Марга IV",
      sector: galaxySectors.valdis,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    207: {
      id: 2,
      name: "Минхир",
      sector: galaxySectors.gellert,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    208: {
      id: 3,
      name: "Минтория",
      sector: galaxySectors.gellert,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    209: {
      id: 2,
      name: "Мордия-9",
      sector: galaxySectors.hawking,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    210: {
      id: 3,
      name: "Нанбатея II",
      sector: galaxySectors.lestrade,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    211: {
      id: 4,
      name: "Нави VII",
      sector: galaxySectors.lestrade,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    212: {
      id: 2,
      name: "Нивель 43",
      sector: galaxySectors.mirin,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    213: {
      id: 3,
      name: "Ошоне",
      imageCount: 2,
      sector: galaxySectors.mirin,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    214: {
      id: 3,
      name: "Оверго-прайм",
      sector: galaxySectors.sten,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    215: {
      id: 5,
      name: "Пандион XXIV",
      sector: galaxySectors.jinXi,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    216: {
      id: 4,
      name: "Партион",
      sector: galaxySectors.sten,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    217: {
      id: 5,
      name: "Пикок",
      sector: galaxySectors.sten,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    218: {
      id: 6,
      name: "Факт-бэй",
      sector: galaxySectors.jinXi,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    219: {
      id: 2,
      name: "Феркад II",
      sector: galaxySectors.farsight,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    220: {
      id: 3,
      name: "Полярис-прайм",
      sector: galaxySectors.farsight,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    221: {
      id: 4,
      name: "Поллукс-31",
      sector: galaxySectors.farsight,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    222: {
      id: 5,
      name: "Праса",
      sector: galaxySectors.farsight,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    223: {
      id: 3,
      name: "Пропус",
      sector: galaxySectors.leo,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    224: {
      id: 4,
      name: "Рас-альгети",
      sector: galaxySectors.leo,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    225: {
      id: 3,
      name: "Арди-4",
      sector: galaxySectors.rigel,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    226: {
      id: 4,
      name: "Роуг 5",
      sector: galaxySectors.rigel,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    227: {
      id: 5,
      name: "Рирга-бэй",
      sector: galaxySectors.rigel,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    228: {
      id: 3,
      name: "Сиэсс",
      sector: galaxySectors.omega,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    229: {
      id: 4,
      name: "Сенже-23",
      sector: galaxySectors.omega,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
    230: {
      id: 5,
      name: "Сетия",
      sector: galaxySectors.omega,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    231: {
      id: 1,
      name: "Шете",
      sector: galaxySectors.xiTauri,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    232: {
      id: 2,
      name: "Симнот",
      sector: galaxySectors.xiTauri,
      biome: biomes.rainForest,
      weatherConditions: [weatherConditions.ionStorms],
    },
    233: {
      id: 3,
      name: "Сириус",
      sector: galaxySectors.xiTauri,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    234: {
      id: 4,
      name: "Скат-бэй",
      sector: galaxySectors.xiTauri,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    235: {
      id: 2,
      name: "Сферион",
      sector: galaxySectors.quintus,
      biome: biomes.jungle,
      weatherConditions: [
        weatherConditions.volcanicActivity,
        weatherConditions.rainstorms,
      ],
    },
    236: {
      id: 3,
      name: "Стор та-прайм",
      sector: galaxySectors.quintus,
      biome: biomes.iceMoss,
      weatherConditions: [weatherConditions.extremeCold],
    },
    237: {
      id: 4,
      name: "Стаут",
      sector: galaxySectors.quintus,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    238: {
      id: 5,
      name: "Термодон",
      sector: galaxySectors.quintus,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    239: {
      id: 4,
      name: "Тибит",
      sector: galaxySectors.severin,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    240: {
      id: 6,
      name: "Тьен-кван",
      tidbit: `
      <p>Тьен-кван - гордый дом знаменитого Моргантонского арсенала, где куют лучшие экзоскелеты! Эти ультрасовременные чудеса были на грани развертывания по всей галактике, пока не налетели эти надоедливые автоматоны, пытаясь забрать то, что принадлежит нам. Но демократия снова восторжествовала, поскольку наши отважные Адские Десантники быстро приступили к действиям, чтобы защитить эту сокровищницу технологий.</p>
      <p>Автоматоны, не подозревавшие о прекрасной возможности, на которую они наткнулись, были быстро уничтожены благодаря молниеносной реакции наших элитных сил. Верховное командование Супер-Земли издало коллективный вздох облегчения, когда 8 марта был освобожден Тьен-кван, обеспечив будущее экзоскелетов EXO-45 Patriot и обеспечив их немедленную доступность для реквизиции нашими доблестными войсками. Еще одна победа Супер-Земли, благодаря непоколебимому мужеству наших Адских Десантников!</p>
    `,
      sector: galaxySectors.theseus,
      biome: biomes.iceMossSpecial,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    241: {
      id: 2,
      name: "Труст",
      sector: galaxySectors.trigon,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    242: {
      id: 5,
      name: "Убанея",
      sector: galaxySectors.severin,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    243: {
      id: 3,
      name: "Устоту",
      sector: galaxySectors.trigon,
      biome: biomes.desert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.tremors,
      ],
    },
    244: {
      id: 4,
      name: "Вандалон IV",
      sector: galaxySectors.trigon,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    245: {
      id: 5,
      name: "Верилия-5",
      sector: galaxySectors.trigon,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    246: {
      id: 2,
      name: "Васат",
      sector: galaxySectors.ymir,
      biome: biomes.toxic,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.acidStorms,
      ],
    },
    247: {
      id: 3,
      name: "Вега-бэй",
      sector: galaxySectors.ymir,
      biome: biomes.winter,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.blizzards,
      ],
    },
    248: {
      id: 4,
      name: "Везен",
      sector: galaxySectors.ymir,
      biome: biomes.desolate,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.fireTornadoes,
      ],
    },
    249: {
      id: 5,
      name: "Виндемитарикс-прайм",
      sector: galaxySectors.valdis,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    250: {
      id: 5,
      name: "Экс-45",
      sector: galaxySectors.ymir,
      biome: biomes.swamp,
      weatherConditions: [weatherConditions.thickFog],
    },
    251: {
      id: 5,
      name: "Йед-приор",
      sector: galaxySectors.tanis,
      biome: biomes.crimsonMoor,
      weatherConditions: [weatherConditions.ionStorms],
    },
    252: {
      id: 6,
      name: "Зефия",
      sector: galaxySectors.tanis,
      biome: biomes.ethereal,
      weatherConditions: [],
    },
    253: {
      id: 4,
      name: "Зосма",
      sector: galaxySectors.gellert,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    254: {
      id: 5,
      name: "Зания-прайм",
      sector: galaxySectors.gellert,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    255: {
      id: 3,
      name: "Скиттер",
      sector: galaxySectors.hawking,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    256: {
      id: 4,
      name: "Эйфория III",
      sector: galaxySectors.hawking,
      biome: biomes.moon,
      weatherConditions: [
        weatherConditions.extremeCold,
        weatherConditions.meteorStorms,
      ],
    },
    257: {
      id: 5,
      name: "Диаспора X",
      sector: galaxySectors.lestrade,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    258: {
      id: 6,
      name: "Самоцветные утесы",
      sector: galaxySectors.lestrade,
      biome: biomes.highlands,
      weatherConditions: [
        weatherConditions.thickFog,
        weatherConditions.rainstorms,
      ],
    },
    259: {
      id: 4,
      name: "Загон-прайм",
      sector: galaxySectors.mirin,
      biome: biomes.newDesert,
      weatherConditions: [
        weatherConditions.intenseHeat,
        weatherConditions.sandstorms,
      ],
    },
    260: {
      id: 7,
      name: "Омикрон",
      sector: galaxySectors.lestrade,
      biome: biomes.tundra,
      weatherConditions: [],
    },
    261: {
      id: 6,
      name: "Киберстан",
      sector: galaxySectors.valdis,
      biome: biomes.canyon,
      weatherConditions: [weatherConditions.tremors],
    },
  };

  constructor() {
    makeAutoObservable(this);
  }

  changeCurrentPlanetInfo(id: number, sector: any) {
    this.currentPlanetInfo = { id: id, sector: sector };
  }

  clearCurrentPlanetInfo() {
    this.currentPlanetInfo = {} as CurrentPlanetInfo;
  }
}

export const planetsStore = new PlanetsStore();
