import { makeAutoObservable } from "mobx";

import { stratagemStore } from "@/store/StratagemStore";

import { ShipModule } from "@/utils/dataInterfaces";

class ShipModulesStore {
  shipModules = [
    {
      id: 1,
      levelImages: [
        "/static/shipModules/PatrioticAdministrationCenterLvl1.webp",
        "/static/shipModules/PatrioticAdministrationCenterLvl2.webp",
        "/static/shipModules/PatrioticAdministrationCenterLvl3.webp",
        "/static/shipModules/PatrioticAdministrationCenterLvl4.webp",
        "/static/shipModules/PatrioticAdministrationCenterLvl5.webp",
      ],
      improvementPrices: [
        {
          commonSampleCount: 60,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 40,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 60,
          superSampleCount: 5,
        },
        {
          commonSampleCount: 150,
          rareSampleCount: 150,
          superSampleCount: 15,
          requisites: 20000,
        },
        {
          commonSampleCount: 200,
          rareSampleCount: 200,
          superSampleCount: 20,
          requisites: 30000,
        },
      ],
      improvementAffectedStratagems: {
        firstLevel: [
          stratagemStore.stratagems[2],
          stratagemStore.stratagems[7],
          stratagemStore.stratagems[10],
          stratagemStore.stratagems[57],
          stratagemStore.stratagems[40],
          stratagemStore.stratagems[39],
          stratagemStore.stratagems[0],
          stratagemStore.stratagems[5],
          stratagemStore.stratagems[1],
        ],
        secondLevel: [
          stratagemStore.stratagems[9],
          stratagemStore.stratagems[2],
          stratagemStore.stratagems[6],
          stratagemStore.stratagems[7],
          stratagemStore.stratagems[8],
          stratagemStore.stratagems[10],
          stratagemStore.stratagems[57],
          stratagemStore.stratagems[40],
          stratagemStore.stratagems[44],
          stratagemStore.stratagems[11],
          stratagemStore.stratagems[39],
          stratagemStore.stratagems[0],
          stratagemStore.stratagems[12],
          stratagemStore.stratagems[5],
          stratagemStore.stratagems[4],
          stratagemStore.stratagems[1],
          stratagemStore.stratagems[3],
          stratagemStore.stratagems[46],
        ],
        thirdLevel: [
          stratagemStore.stratagems[47],
          stratagemStore.stratagems[59],
          stratagemStore.stratagems[51],
          stratagemStore.stratagems[43],
          stratagemStore.stratagems[38],
          stratagemStore.stratagems[42],
          stratagemStore.stratagems[25],
          stratagemStore.stratagems[58],
        ],
        fourthLevel: [stratagemStore.stratagems[64]],
        fifthLevel: [
          stratagemStore.stratagems[2],
          stratagemStore.stratagems[6],
          stratagemStore.stratagems[7],
          stratagemStore.stratagems[8],
          stratagemStore.stratagems[10],
          stratagemStore.stratagems[57],
          stratagemStore.stratagems[40],
          stratagemStore.stratagems[11],
          stratagemStore.stratagems[39],
          stratagemStore.stratagems[0],
          stratagemStore.stratagems[12],
          stratagemStore.stratagems[5],
          stratagemStore.stratagems[4],
          stratagemStore.stratagems[1],
        ],
      },
    },
    {
      id: 2,
      levelImages: [
        "/static/shipModules/OrbitalCannonsLvl1.webp",
        "/static/shipModules/OrbitalCannonsLvl2.webp",
        "/static/shipModules/OrbitalCannonsLvl3.webp",
        "/static/shipModules/OrbitalCannonsLvl4.webp",
        "/static/shipModules/OrbitalCannonsLvl5.webp",
      ],
      improvementPrices: [
        {
          commonSampleCount: 100,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 60,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 80,
          superSampleCount: 10,
        },
        {
          commonSampleCount: 200,
          rareSampleCount: 150,
          superSampleCount: 15,
          requisites: 25000,
        },
        {
          commonSampleCount: 250,
          rareSampleCount: 200,
          superSampleCount: 20,
          requisites: 35000,
        },
      ],
      improvementAffectedStratagems: {
        firstLevel: [
          stratagemStore.stratagems[17],
          stratagemStore.stratagems[20],
          stratagemStore.stratagems[14],
          stratagemStore.stratagems[19],
          stratagemStore.stratagems[30],
          stratagemStore.stratagems[16],
          stratagemStore.stratagems[15],
        ],
        secondLevel: [
          stratagemStore.stratagems[13],
          stratagemStore.stratagems[17],
          stratagemStore.stratagems[19],
          stratagemStore.stratagems[16],
          stratagemStore.stratagems[15],
        ],
        thirdLevel: [
          stratagemStore.stratagems[13],
          stratagemStore.stratagems[17],
          stratagemStore.stratagems[32],
          stratagemStore.stratagems[31],
          stratagemStore.stratagems[20],
          stratagemStore.stratagems[33],
          stratagemStore.stratagems[14],
          stratagemStore.stratagems[19],
          stratagemStore.stratagems[18],
          stratagemStore.stratagems[30],
          stratagemStore.stratagems[16],
          stratagemStore.stratagems[15],
        ],
        fourthLevel: [
          stratagemStore.stratagems[16],
          stratagemStore.stratagems[15],
        ],
        fifthLevel: [
          stratagemStore.stratagems[17],
          stratagemStore.stratagems[19],
          stratagemStore.stratagems[30],
          stratagemStore.stratagems[16],
          stratagemStore.stratagems[15],
        ],
      },
    },
    {
      id: 3,
      levelImages: [
        "/static/shipModules/HangarLvl1.webp",
        "/static/shipModules/HangarLvl2.webp",
        "/static/shipModules/HangarLvl3.webp",
        "/static/shipModules/HangarLvl4.webp",
        "/static/shipModules/HangarLvl5.webp",
      ],
      improvementPrices: [
        {
          commonSampleCount: 80,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 40,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 80,
          superSampleCount: 10,
        },
        {
          commonSampleCount: 150,
          rareSampleCount: 150,
          superSampleCount: 15,
          requisites: 25000,
        },
        {
          commonSampleCount: 200,
          rareSampleCount: 250,
          superSampleCount: 25,
          requisites: 30000,
        },
      ],
      improvementAffectedStratagems: {
        firstLevel: [
          stratagemStore.stratagems[28],
          stratagemStore.stratagems[22],
          stratagemStore.stratagems[21],
          stratagemStore.stratagems[26],
          stratagemStore.stratagems[23],
          stratagemStore.stratagems[24],
          stratagemStore.stratagems[27],
        ],
        secondLevel: [],
        thirdLevel: [
          stratagemStore.stratagems[28],
          stratagemStore.stratagems[22],
          stratagemStore.stratagems[21],
          stratagemStore.stratagems[26],
          stratagemStore.stratagems[23],
          stratagemStore.stratagems[24],
          stratagemStore.stratagems[27],
        ],
        fourthLevel: [
          stratagemStore.stratagems[22],
          stratagemStore.stratagems[26],
          stratagemStore.stratagems[23],
          stratagemStore.stratagems[24],
        ],
        fifthLevel: [],
      },
    },
    {
      id: 4,
      levelImages: [
        "/static/shipModules/BridgeLvl1.webp",
        "/static/shipModules/BridgeLvl2.webp",
        "/static/shipModules/BridgeLvl3.webp",
        "/static/shipModules/BridgeLvl4.webp",
        "/static/shipModules/BridgeLvl5.webp",
      ],
      improvementPrices: [
        {
          commonSampleCount: 60,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 40,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 80,
          superSampleCount: 10,
        },
        {
          commonSampleCount: 200,
          rareSampleCount: 150,
          superSampleCount: 15,
          requisites: 25000,
        },
        {
          commonSampleCount: 250,
          rareSampleCount: 200,
          superSampleCount: 20,
          requisites: 35000,
        },
      ],
      improvementAffectedStratagems: {
        firstLevel: [
          stratagemStore.stratagems[13],
          stratagemStore.stratagems[17],
          stratagemStore.stratagems[32],
          stratagemStore.stratagems[31],
          stratagemStore.stratagems[20],
          stratagemStore.stratagems[33],
          stratagemStore.stratagems[14],
          stratagemStore.stratagems[19],
          stratagemStore.stratagems[18],
          stratagemStore.stratagems[30],
          stratagemStore.stratagems[15],
          stratagemStore.stratagems[16],
        ],
        secondLevel: [],
        thirdLevel: [],
        fourthLevel: [
          stratagemStore.stratagems[60],
          stratagemStore.stratagems[19],
          stratagemStore.stratagems[5],
          stratagemStore.stratagems[24],
          stratagemStore.stratagems[41],
        ],
        fifthLevel: [],
      },
    },
    {
      id: 5,
      levelImages: [
        "/static/shipModules/EngineerBayLvl1.webp",
        "/static/shipModules/EngineerBayLvl2.webp",
        "/static/shipModules/EngineerBayLvl3.webp",
        "/static/shipModules/EngineerBayLvl4.webp",
        "/static/shipModules/EngineerBayLvl5.webp",
      ],
      improvementPrices: [
        {
          commonSampleCount: 60,
          rareSampleCount: 10,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 60,
          superSampleCount: 5,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 80,
          superSampleCount: 10,
        },
        {
          commonSampleCount: 200,
          rareSampleCount: 150,
          superSampleCount: 20,
          requisites: 20000,
        },
        {
          commonSampleCount: 250,
          rareSampleCount: 200,
          superSampleCount: 25,
          requisites: 30000,
        },
      ],
      improvementAffectedStratagems: {
        firstLevel: [
          stratagemStore.stratagems[60],
          stratagemStore.stratagems[61],
          stratagemStore.stratagems[45],
          stratagemStore.stratagems[35],
          stratagemStore.stratagems[64],
          stratagemStore.stratagems[54],
          stratagemStore.stratagems[53],
          stratagemStore.stratagems[49],
          stratagemStore.stratagems[36],
          stratagemStore.stratagems[37],
          stratagemStore.stratagems[48],
          stratagemStore.stratagems[52],
          stratagemStore.stratagems[41],
          stratagemStore.stratagems[34],
        ],
        secondLevel: [
          stratagemStore.stratagems[60],
          stratagemStore.stratagems[54],
          stratagemStore.stratagems[53],
          stratagemStore.stratagems[49],
          stratagemStore.stratagems[36],
          stratagemStore.stratagems[50],
          stratagemStore.stratagems[48],
          stratagemStore.stratagems[52],
        ],
        thirdLevel: [
          stratagemStore.stratagems[61],
          stratagemStore.stratagems[45],
          stratagemStore.stratagems[35],
          stratagemStore.stratagems[36],
          stratagemStore.stratagems[37],
          stratagemStore.stratagems[41],
          stratagemStore.stratagems[34],
        ],
        fourthLevel: [
          stratagemStore.stratagems[44],
          stratagemStore.stratagems[36],
        ],
        fifthLevel: [
          stratagemStore.stratagems[9],
          stratagemStore.stratagems[2],
          stratagemStore.stratagems[6],
          stratagemStore.stratagems[7],
          stratagemStore.stratagems[8],
          stratagemStore.stratagems[10],
          stratagemStore.stratagems[57],
          stratagemStore.stratagems[40],
          stratagemStore.stratagems[44],
          stratagemStore.stratagems[11],
          stratagemStore.stratagems[39],
          stratagemStore.stratagems[0],
          stratagemStore.stratagems[12],
          stratagemStore.stratagems[5],
          stratagemStore.stratagems[4],
          stratagemStore.stratagems[1],
          stratagemStore.stratagems[3],
          stratagemStore.stratagems[46],
        ],
      },
    },
    {
      id: 6,
      levelImages: [
        "/static/shipModules/RoboticsWorkshopLvl1.webp",
        "/static/shipModules/RoboticsWorkshopLvl2.webp",
        "/static/shipModules/RoboticsWorkshopLvl3.webp",
        "/static/shipModules/RoboticsWorkshopLvl4.webp",
        "/static/shipModules/RoboticsWorkshopLvl5.webp",
      ],
      improvementPrices: [
        {
          commonSampleCount: 60,
          rareSampleCount: 20,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 40,
          superSampleCount: 5,
        },
        {
          commonSampleCount: 80,
          rareSampleCount: 80,
          superSampleCount: 10,
        },
        {
          commonSampleCount: 150,
          rareSampleCount: 150,
          superSampleCount: 20,
          requisites: 25000,
        },
        {
          commonSampleCount: 250,
          rareSampleCount: 200,
          superSampleCount: 30,
          requisites: 35000,
        },
      ],
      improvementAffectedStratagems: {
        firstLevel: [
          stratagemStore.stratagems[60],
          stratagemStore.stratagems[54],
          stratagemStore.stratagems[53],
          stratagemStore.stratagems[49],
          stratagemStore.stratagems[50],
          stratagemStore.stratagems[48],
          stratagemStore.stratagems[52],
        ],
        secondLevel: [
          stratagemStore.stratagems[60],
          stratagemStore.stratagems[54],
          stratagemStore.stratagems[53],
          stratagemStore.stratagems[49],
          stratagemStore.stratagems[50],
          stratagemStore.stratagems[48],
          stratagemStore.stratagems[52],
        ],
        thirdLevel: [
          stratagemStore.stratagems[60],
          stratagemStore.stratagems[54],
          stratagemStore.stratagems[53],
          stratagemStore.stratagems[49],
          stratagemStore.stratagems[50],
          stratagemStore.stratagems[48],
          stratagemStore.stratagems[52],
        ],
        fourthLevel: [
          stratagemStore.stratagems[60],
          stratagemStore.stratagems[54],
          stratagemStore.stratagems[53],
          stratagemStore.stratagems[49],
          stratagemStore.stratagems[36],
          stratagemStore.stratagems[50],
          stratagemStore.stratagems[48],
          stratagemStore.stratagems[52],
        ],
        fifthLevel: [
          stratagemStore.stratagems[54],
          stratagemStore.stratagems[50],
        ],
      },
    },
  ] as ShipModule[];

  constructor() {
    makeAutoObservable(this);
  }
}

export const shipModulesStore = new ShipModulesStore();
