import { makeAutoObservable } from "mobx";

import { weaponTypes } from "@/data/weaponTypes";

import {
  CurrentWeaponInfo,
  Grenade,
  PrimaryOrSecondaryWeapon,
  SupportWeapon,
} from "@/utils/storeInterfaces";
import { WeaponType } from "@/utils/dataInterfaces";
import { stratagemStore } from "@/store/StratagemStore";
import { obtainingTypes } from "@/data/obtainingTypes";

class WeaponsStore {
  currentWeaponInfo = {} as CurrentWeaponInfo;

  weapons = [
    {
      id: 1,
      imagePath: "/static/Weaponry/primary/AR23.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "AR-23 Liberator",
      price: 0,
      damage: 60,
      magsCount: 7,
      roundsPerMag: 45,
      totalRounds: 315,
      recoil: 15,
      fireRate: 320,
      totalDamage: 18900,
      dps: 526,
      obtainingTypeIcon: obtainingTypes[0].icon,
    },
    {
      id: 2,
      imagePath: "/static/Weaponry/primary/AR23P.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "AR-23P Liberator Penetrator",
      price: 40,
      damage: 45,
      magsCount: 10,
      roundsPerMag: 30,
      totalRounds: 300,
      recoil: 19,
      fireRate: 640,
      totalDamage: 13500,
      dps: 372,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 3,
      imagePath: "/static/Weaponry/primary/AR23C.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "AR-23C Liberator Concussive",
      price: 20,
      damage: 65,
      magsCount: 10,
      roundsPerMag: 30,
      totalRounds: 300,
      recoil: 28,
      fireRate: 320,
      totalDamage: 19500,
      dps: 296,
      obtainingTypeIcon: obtainingTypes[6].icon,
    },
    {
      id: 4,
      imagePath: "/static/Weaponry/primary/AR23A.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "AR-23A Liberator Carbine",
      price: 20,
      damage: 60,
      magsCount: 7,
      roundsPerMag: 45,
      totalRounds: 315,
      recoil: 26,
      fireRate: 920,
      totalDamage: 18900,
      dps: 526,
      obtainingTypeIcon: obtainingTypes[10].icon,
    },
    {
      id: 5,
      imagePath: "/static/Weaponry/primary/AR61.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "AR-61 Tenderizer",
      price: 20,
      damage: 60,
      magsCount: 10,
      roundsPerMag: 35,
      totalRounds: 350,
      recoil: 10,
      fireRate: 600,
      totalDamage: 21000,
      dps: 475,
      obtainingTypeIcon: obtainingTypes[9].icon,
    },
    {
      id: 6,
      imagePath: "/static/Weaponry/primary/STA52.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "StA-52 Assault Rifle",
      price: 20,
      damage: 70,
      magsCount: 8,
      roundsPerMag: 56,
      totalRounds: 200,
      recoil: 19,
      fireRate: 790,
      totalDamage: 16000,
      dps: 577,
      obtainingTypeIcon: obtainingTypes[8].icon,
    },
    {
      id: 7,
      imagePath: "/static/Weaponry/primary/BR14.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "BR-14 Adjudicator",
      price: 20,
      damage: 80,
      magsCount: 8,
      roundsPerMag: 25,
      totalRounds: 200,
      recoil: 40,
      fireRate: 550,
      totalDamage: 16000,
      dps: 577,
      obtainingTypeIcon: obtainingTypes[8].icon,
    },
    {
      id: 8,
      imagePath: "/static/Weaponry/primary/R2124.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "R-2124 Constitution",
      price: 0,
      damage: 180,
      magsCount: 8,
      roundsPerMag: 5,
      totalRounds: 160,
      recoil: 43,
      fireRate: 60,
      totalDamage: 20000,
      dps: 581,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 9,
      imagePath: "/static/Weaponry/primary/R63.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "R-63 Diligence",
      price: 8,
      damage: 125,
      magsCount: 8,
      roundsPerMag: 20,
      totalRounds: 160,
      recoil: 35,
      fireRate: 350,
      totalDamage: 20000,
      dps: 581,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 10,
      imagePath: "/static/Weaponry/primary/R63CS.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "R-63CS Diligence Counter Sniper",
      price: 40,
      damage: 140,
      magsCount: 6,
      roundsPerMag: 15,
      totalRounds: 90,
      recoil: 53,
      fireRate: 350,
      totalDamage: 12600,
      dps: 622,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 11,
      imagePath: "/static/Weaponry/primary/PLAS39.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "PLAS-39 Accelerator Rifle",
      price: 0,
      damage: 350,
      magsCount: 6,
      roundsPerMag: 9,
      totalRounds: 90,
      recoil: 3,
      fireRate: 550,
      totalDamage: 12600,
      dps: 622,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 12,
      imagePath: "/static/Weaponry/primary/SMG32.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SMG-32 Reprimand",
      price: 40,
      damage: 140,
      magsCount: 6,
      roundsPerMag: 15,
      totalRounds: 90,
      recoil: 53,
      fireRate: 350,
      totalDamage: 12600,
      dps: 622,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 13,
      imagePath: "/static/Weaponry/primary/SMG37.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SMG-37 Defender",
      price: 15,
      damage: 70,
      magsCount: 7,
      roundsPerMag: 45,
      totalRounds: 315,
      recoil: 10,
      fireRate: 520,
      totalDamage: 22050,
      dps: 519,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 14,
      imagePath: "/static/Weaponry/primary/SMG72.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SMG-72 Pummeler",
      price: 60,
      damage: 65,
      magsCount: 7,
      roundsPerMag: 45,
      totalRounds: 315,
      recoil: 10,
      fireRate: 475,
      totalDamage: 20475,
      dps: 426,
      obtainingTypeIcon: obtainingTypes[9].icon,
    },
    {
      id: 15,
      imagePath: "/static/Weaponry/primary/STA11.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "StA-11 SMG",
      price: 0,
      damage: 65,
      magsCount: 7,
      roundsPerMag: 48,
      totalRounds: 350,
      recoil: 13,
      fireRate: 1050,
      totalDamage: 17500,
      dps: 871,
      obtainingTypeIcon: obtainingTypes[3].icon,
    },
    {
      id: 16,
      imagePath: "/static/Weaponry/primary/MP98.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "MP-98 Knight",
      price: "Издание Super-Citizen",
      damage: 50,
      magsCount: 7,
      roundsPerMag: 50,
      totalRounds: 350,
      recoil: 20,
      fireRate: 1380,
      totalDamage: 17500,
      dps: 871,
      obtainingTypeIcon: obtainingTypes[3].icon,
    },
    {
      id: 17,
      imagePath: "/static/Weaponry/primary/SG8.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SG-8 Punisher",
      price: 4,
      damage: 405,
      magsCount: 3.75,
      roundsPerMag: 16,
      totalRounds: 60,
      recoil: 120,
      fireRate: 80,
      totalDamage: 24300,
      dps: 447,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 18,
      imagePath: "/static/Weaponry/primary/SG8S.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SG-8S Slugger",
      price: 60,
      damage: 280,
      magsCount: 3.75,
      roundsPerMag: 16,
      totalRounds: 60,
      recoil: 120,
      fireRate: 80,
      totalDamage: 15000,
      dps: 276,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 19,
      imagePath: "/static/Weaponry/primary/SG451.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SG-451 Cookout",
      price: 60,
      damage: 320,
      magsCount: 3.75,
      roundsPerMag: 16,
      totalRounds: 60,
      recoil: 100,
      fireRate: 80,
      totalDamage: 15000,
      dps: 276,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 20,
      imagePath: "/static/Weaponry/primary/SG20.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SG-20 Halt",
      price: 20,
      damage: 280,
      magsCount: 3.75,
      roundsPerMag: 16,
      totalRounds: 60,
      recoil: 120,
      fireRate: 80,
      totalDamage: 15000,
      dps: 276,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 21,
      imagePath: "/static/Weaponry/primary/SG225.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SG-225 Breaker",
      price: 20,
      damage: 330,
      magsCount: 7,
      roundsPerMag: 13,
      totalRounds: 91,
      recoil: 55,
      fireRate: 300,
      totalDamage: 30030,
      dps: 1263,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 22,
      imagePath: "/static/Weaponry/primary/SG225IE.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SG-225IE Breaker Incendiary",
      price: 60,
      damage: 180,
      magsCount: 6,
      roundsPerMag: 25,
      totalRounds: 150,
      recoil: 28,
      fireRate: 300,
      totalDamage: 36000,
      dps: 1011,
      obtainingTypeIcon: obtainingTypes[6].icon,
    },
    {
      id: 23,
      imagePath: "/static/Weaponry/primary/SG225SP.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SG-225SP Breaker Spray&Pray",
      price: 60,
      damage: 192,
      magsCount: 8,
      roundsPerMag: 26,
      totalRounds: 208,
      recoil: 28,
      fireRate: 330,
      totalDamage: 39936,
      dps: 851,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 24,
      imagePath: "/static/Weaponry/primary/Cb9.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "CB-9 Exploding Crossbow",
      price: 80,
      damage: 420,
      magsCount: 8,
      roundsPerMag: 5,
      totalRounds: 40,
      recoil: 35,
      fireRate: 50,
      totalDamage: 16800,
      dps: 299,
      obtainingTypeIcon: obtainingTypes[8].icon,
    },
    {
      id: 25,
      imagePath: "/static/Weaponry/primary/R36.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "R-36 Eruptor",
      price: 60,
      damage: 420,
      magsCount: 6,
      roundsPerMag: 5,
      totalRounds: 30,
      recoil: 75,
      fireRate: 25,
      totalDamage: 12600,
      dps: 157,
      obtainingTypeIcon: obtainingTypes[8].icon,
    },
    {
      id: 26,
      imagePath: "/static/Weaponry/primary/LAS5.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "LAS-5 Scythe",
      price: 30,
      damage: 350,
      magsCount: 8,
      roundsPerMag: 8,
      totalRounds: 64,
      recoil: 1,
      fireRate: 1,
      totalDamage: 22400,
      dps: 322,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 27,
      imagePath: "/static/Weaponry/primary/LAS16.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "LAS-16 Sickle",
      price: 20,
      damage: 55,
      magsCount: 3,
      roundsPerMag: 9,
      totalRounds: 45,
      recoil: 2,
      fireRate: 750,
      totalDamage: 1485,
      dps: 433,
      obtainingTypeIcon: obtainingTypes[7].icon,
    },
    {
      id: 28,
      imagePath: "/static/Weaponry/primary/PLAS1.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "PLAS-1 Scorcher",
      price: 60,
      damage: 200,
      magsCount: 6,
      roundsPerMag: 15,
      totalRounds: 90,
      recoil: 20,
      fireRate: 250,
      totalDamage: 18000,
      dps: 671,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 29,
      imagePath: "/static/Weaponry/primary/PLAS101.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "PLAS-101 Purifier",
      price: 80,
      damage: 250,
      magsCount: 6,
      roundsPerMag: 15,
      totalRounds: 90,
      recoil: 20,
      fireRate: 250,
      totalDamage: 22500,
      dps: 847,
      obtainingTypeIcon: obtainingTypes[9].icon,
    },
    {
      id: 30,
      imagePath: "/static/Weaponry/primary/SG8P.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "SG-8P Punisher Plasma",
      price: 60,
      damage: 250,
      magsCount: 8,
      roundsPerMag: 8,
      totalRounds: 64,
      recoil: 110,
      fireRate: 80,
      totalDamage: 16000,
      dps: 289,
      obtainingTypeIcon: obtainingTypes[7].icon,
    },
    {
      id: 31,
      imagePath: "/static/Weaponry/primary/ARC12.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "ARC-12 Blitzer",
      price: 80,
      damage: 250,
      magsCount: 1,
      roundsPerMag: 1,
      totalRounds: 1,
      recoil: 60,
      fireRate: 45,
      totalDamage: Infinity,
      dps: 142,
      obtainingTypeIcon: obtainingTypes[7].icon,
    },
    {
      id: 32,
      imagePath: "/static/Weaponry/primary/JAR5.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "JAR-5 Dominator",
      price: 80,
      damage: 275,
      magsCount: 6,
      roundsPerMag: 15,
      totalRounds: 90,
      recoil: 75,
      fireRate: 250,
      totalDamage: 24750,
      dps: 876,
      obtainingTypeIcon: obtainingTypes[6].icon,
    },
    {
      id: 33,
      imagePath: "/static/Weaponry/primary/FLAM66.webp",
      weaponType: weaponTypes.primary,
      typeIndex: 1,
      devName: "FLAM-66 Torcher",
      price: 80,
      damage: 375,
      magsCount: 1,
      roundsPerMag: 80,
      totalRounds: 1,
      recoil: 2,
      fireRate: 45,
      totalDamage: Infinity,
      dps: 142,
      obtainingTypeIcon: obtainingTypes[7].icon,
    },
    {
      id: 34,
      imagePath: "/static/Weaponry/secondary/P2.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "P-2 Peacemaker",
      price: 0,
      damage: 75,
      magsCount: 4,
      roundsPerMag: 15,
      totalRounds: 60,
      recoil: 23,
      fireRate: 900,
      totalDamage: 3600,
      dps: 643,
      obtainingTypeIcon: obtainingTypes[0].icon,
    },
    {
      id: 35,
      imagePath: "/static/Weaponry/secondary/P4.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "P-4 Senator",
      price: 15,
      damage: 175,
      magsCount: 3.33,
      roundsPerMag: 6,
      totalRounds: 20,
      recoil: 43,
      fireRate: 200,
      totalDamage: 3000,
      dps: 299,
      obtainingTypeIcon: obtainingTypes[6].icon,
    },
    {
      id: 36,
      imagePath: "/static/Weaponry/secondary/P11.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "P-11 Stim Pistol",
      price: 5,
      damage: 0,
      magsCount: 4,
      roundsPerMag: 6,
      totalRounds: 124,
      recoil: 6,
      fireRate: 70,
      totalDamage: 7440,
      dps: 841,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 37,
      imagePath: "/static/Weaponry/secondary/P19.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "P-19 Redeemer",
      price: 5,
      damage: 60,
      magsCount: 4,
      roundsPerMag: 31,
      totalRounds: 124,
      recoil: 11,
      fireRate: 1100,
      totalDamage: 7440,
      dps: 841,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 38,
      imagePath: "/static/Weaponry/secondary/P72.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "P-72 Crisper",
      price: 5,
      damage: 60,
      magsCount: 4,
      roundsPerMag: 31,
      totalRounds: 124,
      recoil: 11,
      fireRate: 1100,
      totalDamage: 7440,
      dps: 841,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 39,
      imagePath: "/static/Weaponry/secondary/P113.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "P-113 Verdict",
      price: 60,
      damage: 125,
      magsCount: 8,
      roundsPerMag: 10,
      totalRounds: 80,
      recoil: 40,
      fireRate: 450,
      totalDamage: 10000,
      dps: 695,
      obtainingTypeIcon: obtainingTypes[9].icon,
    },
    {
      id: 40,
      imagePath: "/static/Weaponry/secondary/GP31.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "GP-31 Grenade Pistol",
      price: 60,
      damage: 600,
      magsCount: 8,
      roundsPerMag: 1,
      totalRounds: 8,
      recoil: 43,
      fireRate: 900,
      totalDamage: 4800,
      dps: 734,
      obtainingTypeIcon: obtainingTypes[8].icon,
    },
    {
      id: 41,
      imagePath: "/static/Weaponry/secondary/SG22.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "SG-22 Bushwhacker",
      price: 50,
      damage: 405,
      magsCount: 8,
      roundsPerMag: 3,
      totalRounds: 30,
      recoil: 170,
      fireRate: 650,
      totalDamage: 10000,
      dps: 695,
      obtainingTypeIcon: obtainingTypes[10].icon,
    },
    {
      id: 42,
      imagePath: "/static/Weaponry/secondary/LAS7.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "LAS-7 Dagger",
      price: 60,
      damage: 200,
      magsCount: 3,
      roundsPerMag: 3,
      totalRounds: 9,
      recoil: 1,
      fireRate: 1,
      totalDamage: 1350,
      dps: 127,
      obtainingTypeIcon: obtainingTypes[7].icon,
    },
    {
      id: 43,
      imagePath: "/static/Weaponry/secondary/PLAS15.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "PLAS-15 Loyalist",
      price: 45,
      damage: 405,
      magsCount: 8,
      roundsPerMag: 3,
      totalRounds: 30,
      recoil: 170,
      fireRate: 650,
      totalDamage: 10000,
      dps: 695,
      obtainingTypeIcon: obtainingTypes[10].icon,
    },
    {
      id: 44,
      imagePath: "/static/Weaponry/secondary/CQC19.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "CQC-19 Stun Lance",
      price: 45,
      damage: 405,
      magsCount: 8,
      roundsPerMag: 3,
      totalRounds: 30,
      recoil: 8,
      fireRate: 650,
      totalDamage: 10000,
      dps: 695,
      obtainingTypeIcon: obtainingTypes[10].icon,
    },
    {
      id: 45,
      imagePath: "/static/Weaponry/secondary/CQC30.webp",
      weaponType: weaponTypes.secondary,
      typeIndex: 2,
      devName: "CQC-30 Stun Baton",
      price: 45,
      damage: 405,
      magsCount: 8,
      roundsPerMag: 3,
      totalRounds: 30,
      recoil: 8,
      fireRate: 650,
      totalDamage: 10000,
      dps: 695,
      obtainingTypeIcon: obtainingTypes[10].icon,
    },
    {
      id: 46,
      imagePath: "/static/Weaponry/grenades/G3.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-3 Smoke",
      price: 25,
      damage: 0,
      fuseTime: 2.4,
      penetration: 0,
      radius: 5,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 47,
      imagePath: "/static/Weaponry/grenades/G4.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-4 Gas",
      price: 25,
      damage: 3,
      fuseTime: 2.9,
      penetration: 6,
      radius: 7,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 48,
      imagePath: "/static/Weaponry/grenades/G6.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-6 Frag",
      price: 2,
      damage: 250,
      fuseTime: 2.4,
      penetration: 3,
      radius: 8,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 49,
      imagePath: "/static/Weaponry/grenades/G10.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-10 Incendiary",
      price: 25,
      damage: 150,
      fuseTime: 2.9,
      penetration: 1,
      radius: 7,
      obtainingTypeIcon: obtainingTypes[6].icon,
    },
    {
      id: 50,
      imagePath: "/static/Weaponry/grenades/G12.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-12 High Explosive",
      price: 0,
      damage: 400,
      fuseTime: 3.5,
      penetration: 4,
      radius: 7,
      obtainingTypeIcon: obtainingTypes[0].icon,
    },
    {
      id: 51,
      imagePath: "/static/Weaponry/grenades/G13.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-13 Incendiary Impact",
      price: 25,
      damage: 150,
      fuseTime: 0.0,
      penetration: 3,
      radius: 7,
      obtainingTypeIcon: obtainingTypes[9].icon,
    },
    {
      id: 52,
      imagePath: "/static/Weaponry/grenades/G16.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-16 Impact",
      price: 20,
      damage: 400,
      fuseTime: 0,
      penetration: 4,
      radius: 7,
      obtainingTypeIcon: obtainingTypes[5].icon,
    },
    {
      id: 53,
      imagePath: "/static/Weaponry/grenades/G23.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-23 Stun",
      price: 20,
      damage: 0,
      fuseTime: 1.8,
      penetration: 6,
      radius: 10,
      obtainingTypeIcon: obtainingTypes[7].icon,
    },
    {
      id: 54,
      imagePath: "/static/Weaponry/grenades/G123.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "G-123 Thermite",
      price: 15,
      damage: 100,
      fuseTime: 2.9,
      penetration: 7,
      radius: 2,
      obtainingTypeIcon: obtainingTypes[8].icon,
    },
    {
      id: 55,
      imagePath: "/static/Weaponry/grenades/K2.webp",
      weaponType: weaponTypes.grenade,
      typeIndex: 3,
      devName: "K-2 Throwing Knife",
      price: 15,
      damage: 250,
      fuseTime: 2.9,
      penetration: 3,
      radius: 2,
      obtainingTypeIcon: obtainingTypes[8].icon,
    },
  ];

  supportWeapons = [
    {
      id: 1,
      imagePath: "/static/Weaponry/support/Mg43Image.webp",
      weaponType: weaponTypes.support,
      name: "MG-43 «Пулемет»",
      description:
        "Стационарный пулемет. Обладает большой огневой мощью, но сильной отдачей и сниженной точностью.",
      price: 0,
      damage: 80,
      magsCount: 2,
      roundsPerMag: 150,
      totalRounds: 300,
      callTime: 3,
      directions: stratagemStore.stratagems[0].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 2,
      imagePath: "/static/Weaponry/support/Apw1Image.webp",
      weaponType: weaponTypes.support,
      name: "APW-1 «Крупнокалиберная винтовка»",
      description:
        "Крупнокалиберная снайперская винтовка, эффективно поражающая легкую бронированную технику на большом расстоянии. Используется только с прицелом.",
      price: 5000,
      damage: 450,
      magsCount: 6,
      roundsPerMag: 7,
      totalRounds: 42,
      callTime: 7,
      directions: stratagemStore.stratagems[1].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 3,
      imagePath: "/static/Weaponry/support/Mg105Image.webp",
      weaponType: weaponTypes.support,
      name: "MG-105 «Доблесть»",
      description:
        "Компактный пулемет малого калибра. Меньшая огневая мощь по сравнению с тяжелыми пулеметами компенсируется удобством использования и быстротой перезарядки.",
      price: 3500,
      damage: 60,
      magsCount: 3,
      roundsPerMag: 250,
      totalRounds: 750,
      callTime: 7,
      directions: stratagemStore.stratagems[2].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 4,
      imagePath: "/static/Weaponry/support/Eat17Image.webp",
      weaponType: weaponTypes.support,
      name: "EAT-17 «Одноразовый бронебой»",
      description:
        "Одноразовое оружие, предназначенное для повреждения бронированной техники. Выбрасывается после использования.",
      price: 3000,
      damage: 650,
      magsCount: 1,
      roundsPerMag: 1,
      totalRounds: 1,
      callTime: 6,
      directions: stratagemStore.stratagems[3].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 5,
      imagePath: "/static/Weaponry/support/Gr8Image.webp",
      weaponType: weaponTypes.support,
      name: "GR-8 «Безоткатная винтовка»",
      description:
        "Безоткатная винтовка, эффективно уничтожающая бронированную технику. В комплекте идет рюкзак поддержки для перезарядки.",
      price: 6000,
      damage: 650,
      magsCount: 10,
      roundsPerMag: 1,
      totalRounds: 10,
      callTime: 7,
      directions: stratagemStore.stratagems[4].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 6,
      imagePath: "/static/Weaponry/support/Flam40Image.webp",
      weaponType: weaponTypes.support,
      name: "FLAM-40 «Огнемет»",
      description:
        "Зажигательное оружие ближнего боя. Поджигает врагов, ландшафт и легковоспламеняющихся союзников.",
      price: 6000,
      damage: null,
      magsCount: 4,
      roundsPerMag: 100,
      totalRounds: 400,
      callTime: 3,
      directions: stratagemStore.stratagems[5].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 7,
      imagePath: "/static/Weaponry/support/Ac8Image.webp",
      weaponType: weaponTypes.support,
      name: "AC-8 «Автопушка»",
      description:
        "Автоматическая пушка, эффективно уничтожающая легкую бронированную технику. Для перезарядки требуется прикладываемый рюкзак поддержки.",
      price: 7000,
      damage: 260,
      magsCount: 10,
      roundsPerMag: 5,
      totalRounds: 50,
      callTime: 7,
      directions: stratagemStore.stratagems[6].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 8,
      imagePath: "/static/Weaponry/support/Mg206Image.webp",
      weaponType: weaponTypes.support,
      name: "MG-206 «Тяжелый пулемет»",
      description:
        "Очень мощный, но сложный в обращении пулемет с сильной отдачей.",
      price: 6000,
      damage: 100,
      magsCount: 2,
      roundsPerMag: 75,
      totalRounds: 150,
      callTime: 7,
      directions: stratagemStore.stratagems[7].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 9,
      imagePath: "/static/Weaponry/support/Rl77Image.webp",
      weaponType: weaponTypes.support,
      name: "RL-77 «Ракетница с подрывом в воздухе»",
      description:
        "Выпускает ракету, которая взрывается при приближении к цели и разбрасывает множество взрывающихся бомб.",
      price: 6000,
      damage: 500,
      magsCount: 2,
      roundsPerMag: 75,
      totalRounds: 150,
      callTime: 7,
      directions: stratagemStore.stratagems[8].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 10,
      imagePath: "/static/Weaponry/support/Rs422Image.webp",
      weaponType: weaponTypes.support,
      name: "RS-422 «Рельсотрон»",
      description:
        "Экспериментальное оружие, отличающееся высокой бронепробивной способностью. Требует зарядки между выстрелами, так что выбирайте цели с умом.",
      price: 10000,
      damage: 600,
      magsCount: 20,
      roundsPerMag: 1,
      totalRounds: 20,
      callTime: 7,
      directions: stratagemStore.stratagems[9].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 11,
      imagePath: "/static/Weaponry/support/SpearImage.webp",
      weaponType: weaponTypes.support,
      name: "FAF-14 «Копье»",
      description:
        "Противотанковая ракета с самонаведением, которую нужно навести на цель перед запуском. Эффективна против больших и бронированных целей.",
      price: 9000,
      damage: 1000,
      magsCount: 3,
      roundsPerMag: 1,
      totalRounds: 3,
      callTime: 3,
      directions: stratagemStore.stratagems[10].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 12,
      imagePath: "/static/Weaponry/support/Gl21Image.webp",
      weaponType: weaponTypes.support,
      name: "GL-21 «Гранатомет»",
      description:
        "Гранатомет, эффективно поражающий бронированную пехоту. Не предназначен для уничтожения бронированной техники или укреплений.",
      price: 6000,
      damage: 350,
      magsCount: 10,
      roundsPerMag: 1,
      totalRounds: 10,
      callTime: 3,
      directions: stratagemStore.stratagems[39].directions,
      features: ["Оружие поддержки", "Адская капсула", "Взрывчатка"],
      obtainingTypeIcon: "",
    },
    {
      id: 13,
      imagePath: "/static/Weaponry/support/Las98Image.webp",
      weaponType: weaponTypes.support,
      name: "LAS-98 «Лазерная пушка»",
      description:
        "Лазерное оружие, стреляющее непрерывным лучом. Не требует перезарядки, но в случае перегрева нужно заменить радиатор.",
      price: 4000,
      damage: 350,
      magsCount: 1,
      roundsPerMag: 1,
      totalRounds: 1,
      callTime: 7,
      directions: stratagemStore.stratagems[40].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 14,
      imagePath: "/static/Weaponry/support/Arc3Image.webp",
      weaponType: weaponTypes.support,
      name: "ARC-3 «Дуговой метатель»",
      description:
        "Выстреливает электрическую дугу на близком расстоянии. Заряжается для стрельбы молниями, способными поразить несколько целей.",
      price: 7000,
      damage: 250,
      magsCount: 1,
      roundsPerMag: 1,
      totalRounds: Infinity,
      callTime: 3,
      directions: stratagemStore.stratagems[44].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
    {
      id: 15,
      imagePath: "/static/Weaponry/support/Las99Image.webp",
      weaponType: weaponTypes.support,
      name: "LAS-99 Пушка «Квазар»",
      description:
        "Заряжается и выпускает мощный взрывающийся сгусток энергии. После выстрела долго перезаряжается.",
      price: 7500,
      damage: 650,
      magsCount: 1,
      roundsPerMag: 1,
      totalRounds: Infinity,
      callTime: 7,
      directions: stratagemStore.stratagems[46].directions,
      features: ["Оружие поддержки", "Адская капсула"],
      obtainingTypeIcon: "",
    },
  ] as SupportWeapon[];

  constructor() {
    makeAutoObservable(this);
  }

  changeCurrentWeaponInfo(id: number, weaponType: WeaponType) {
    this.currentWeaponInfo = { id: id, weaponType: weaponType };
  }

  clearCurrentWeaponInfo() {
    this.currentWeaponInfo = {} as CurrentWeaponInfo;
  }
}

export const weaponsStore = new WeaponsStore();
